// Code generated by Kitex v0.16.3. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	yim "github.com/yim/kitex_gen/yim"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, Req *yim.SendMessageReq, callOptions ...callopt.Option) (r *yim.SendMessageRsp, err error)
	PullHistory(ctx context.Context, Req *yim.PullHistoryReq, callOptions ...callopt.Option) (r *yim.PullHistoryRsp, err error)
	Sync(ctx context.Context, Req *yim.SyncReq2, callOptions ...callopt.Option) (r *yim.SyncRsp2, err error)
	AckPush(ctx context.Context, Req *yim.AckPushReq, callOptions ...callopt.Option) (r *yim.AckPushRsp, err error)
	RevokeMessage(ctx context.Context, Req *yim.RevokeMessageReq, callOptions ...callopt.Option) (r *yim.RevokeMessageRsp, err error)
	MarkRead(ctx context.Context, Req *yim.MarkReadReq, callOptions ...callopt.Option) (r *yim.MarkReadRsp, err error)
	GetReadState(ctx context.Context, Req *yim.GetReadStateReq, callOptions ...callopt.Option) (r *yim.GetReadStateRsp, err error)
	ListConversations(ctx context.Context, Req *yim.ListConversationsReq, callOptions ...callopt.Option) (r *yim.ListConversationsRsp, err error)
	SearchMessages(ctx context.Context, Req *yim.SearchMessagesReq, callOptions ...callopt.Option) (r *yim.SearchMessagesRsp, err error)
	CreateConv(ctx context.Context, Req *yim.CreateConvReq, callOptions ...callopt.Option) (r *yim.CreateConvRsp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) SendMessage(ctx context.Context, Req *yim.SendMessageReq, callOptions ...callopt.Option) (r *yim.SendMessageRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, Req)
}

func (p *kMessageServiceClient) PullHistory(ctx context.Context, Req *yim.PullHistoryReq, callOptions ...callopt.Option) (r *yim.PullHistoryRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PullHistory(ctx, Req)
}

func (p *kMessageServiceClient) Sync(ctx context.Context, Req *yim.SyncReq2, callOptions ...callopt.Option) (r *yim.SyncRsp2, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Sync(ctx, Req)
}

func (p *kMessageServiceClient) AckPush(ctx context.Context, Req *yim.AckPushReq, callOptions ...callopt.Option) (r *yim.AckPushRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AckPush(ctx, Req)
}

func (p *kMessageServiceClient) RevokeMessage(ctx context.Context, Req *yim.RevokeMessageReq, callOptions ...callopt.Option) (r *yim.RevokeMessageRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeMessage(ctx, Req)
}

func (p *kMessageServiceClient) MarkRead(ctx context.Context, Req *yim.MarkReadReq, callOptions ...callopt.Option) (r *yim.MarkReadRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkRead(ctx, Req)
}

func (p *kMessageServiceClient) GetReadState(ctx context.Context, Req *yim.GetReadStateReq, callOptions ...callopt.Option) (r *yim.GetReadStateRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetReadState(ctx, Req)
}

func (p *kMessageServiceClient) ListConversations(ctx context.Context, Req *yim.ListConversationsReq, callOptions ...callopt.Option) (r *yim.ListConversationsRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversations(ctx, Req)
}

func (p *kMessageServiceClient) SearchMessages(ctx context.Context, Req *yim.SearchMessagesReq, callOptions ...callopt.Option) (r *yim.SearchMessagesRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchMessages(ctx, Req)
}

func (p *kMessageServiceClient) CreateConv(ctx context.Context, Req *yim.CreateConvReq, callOptions ...callopt.Option) (r *yim.CreateConvRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateConv(ctx, Req)
}
