// Code generated by Kitex v0.16.3. DO NOT EDIT.

package messageservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	yim "github.com/yim/kitex_gen/yim"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendMessage": kitex.NewMethodInfo(
		sendMessageHandler,
		newSendMessageArgs,
		newSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"PullHistory": kitex.NewMethodInfo(
		pullHistoryHandler,
		newPullHistoryArgs,
		newPullHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Sync": kitex.NewMethodInfo(
		syncHandler,
		newSyncArgs,
		newSyncResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AckPush": kitex.NewMethodInfo(
		ackPushHandler,
		newAckPushArgs,
		newAckPushResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RevokeMessage": kitex.NewMethodInfo(
		revokeMessageHandler,
		newRevokeMessageArgs,
		newRevokeMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MarkRead": kitex.NewMethodInfo(
		markReadHandler,
		newMarkReadArgs,
		newMarkReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetReadState": kitex.NewMethodInfo(
		getReadStateHandler,
		newGetReadStateArgs,
		newGetReadStateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListConversations": kitex.NewMethodInfo(
		listConversationsHandler,
		newListConversationsArgs,
		newListConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchMessages": kitex.NewMethodInfo(
		searchMessagesHandler,
		newSearchMessagesArgs,
		newSearchMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateConv": kitex.NewMethodInfo(
		createConvHandler,
		newCreateConvArgs,
		newCreateConvResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	messageServiceServiceInfo                = NewServiceInfo()
	messageServiceServiceInfoForClient       = NewServiceInfoForClient()
	messageServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return messageServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return messageServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*yim.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yim",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.SendMessageReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).SendMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SendMessageArgs:
		success, err := handler.(yim.MessageService).SendMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SendMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSendMessageArgs() interface{} {
	return &SendMessageArgs{}
}

func newSendMessageResult() interface{} {
	return &SendMessageResult{}
}

type SendMessageArgs struct {
	Req *yim.SendMessageReq
}

func (p *SendMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SendMessageArgs) Unmarshal(in []byte) error {
	msg := new(yim.SendMessageReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SendMessageArgs_Req_DEFAULT *yim.SendMessageReq

func (p *SendMessageArgs) GetReq() *yim.SendMessageReq {
	if !p.IsSetReq() {
		return SendMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SendMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SendMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SendMessageResult struct {
	Success *yim.SendMessageRsp
}

var SendMessageResult_Success_DEFAULT *yim.SendMessageRsp

func (p *SendMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SendMessageResult) Unmarshal(in []byte) error {
	msg := new(yim.SendMessageRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SendMessageResult) GetSuccess() *yim.SendMessageRsp {
	if !p.IsSetSuccess() {
		return SendMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SendMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.SendMessageRsp)
}

func (p *SendMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SendMessageResult) GetResult() interface{} {
	return p.Success
}

func pullHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.PullHistoryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).PullHistory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PullHistoryArgs:
		success, err := handler.(yim.MessageService).PullHistory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PullHistoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPullHistoryArgs() interface{} {
	return &PullHistoryArgs{}
}

func newPullHistoryResult() interface{} {
	return &PullHistoryResult{}
}

type PullHistoryArgs struct {
	Req *yim.PullHistoryReq
}

func (p *PullHistoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PullHistoryArgs) Unmarshal(in []byte) error {
	msg := new(yim.PullHistoryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PullHistoryArgs_Req_DEFAULT *yim.PullHistoryReq

func (p *PullHistoryArgs) GetReq() *yim.PullHistoryReq {
	if !p.IsSetReq() {
		return PullHistoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PullHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PullHistoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PullHistoryResult struct {
	Success *yim.PullHistoryRsp
}

var PullHistoryResult_Success_DEFAULT *yim.PullHistoryRsp

func (p *PullHistoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PullHistoryResult) Unmarshal(in []byte) error {
	msg := new(yim.PullHistoryRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PullHistoryResult) GetSuccess() *yim.PullHistoryRsp {
	if !p.IsSetSuccess() {
		return PullHistoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PullHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.PullHistoryRsp)
}

func (p *PullHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PullHistoryResult) GetResult() interface{} {
	return p.Success
}

func syncHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.SyncReq2)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).Sync(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SyncArgs:
		success, err := handler.(yim.MessageService).Sync(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SyncResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSyncArgs() interface{} {
	return &SyncArgs{}
}

func newSyncResult() interface{} {
	return &SyncResult{}
}

type SyncArgs struct {
	Req *yim.SyncReq2
}

func (p *SyncArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SyncArgs) Unmarshal(in []byte) error {
	msg := new(yim.SyncReq2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SyncArgs_Req_DEFAULT *yim.SyncReq2

func (p *SyncArgs) GetReq() *yim.SyncReq2 {
	if !p.IsSetReq() {
		return SyncArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SyncArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SyncArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SyncResult struct {
	Success *yim.SyncRsp2
}

var SyncResult_Success_DEFAULT *yim.SyncRsp2

func (p *SyncResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SyncResult) Unmarshal(in []byte) error {
	msg := new(yim.SyncRsp2)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SyncResult) GetSuccess() *yim.SyncRsp2 {
	if !p.IsSetSuccess() {
		return SyncResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SyncResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.SyncRsp2)
}

func (p *SyncResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SyncResult) GetResult() interface{} {
	return p.Success
}

func ackPushHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.AckPushReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).AckPush(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AckPushArgs:
		success, err := handler.(yim.MessageService).AckPush(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AckPushResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAckPushArgs() interface{} {
	return &AckPushArgs{}
}

func newAckPushResult() interface{} {
	return &AckPushResult{}
}

type AckPushArgs struct {
	Req *yim.AckPushReq
}

func (p *AckPushArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AckPushArgs) Unmarshal(in []byte) error {
	msg := new(yim.AckPushReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AckPushArgs_Req_DEFAULT *yim.AckPushReq

func (p *AckPushArgs) GetReq() *yim.AckPushReq {
	if !p.IsSetReq() {
		return AckPushArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AckPushArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AckPushArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AckPushResult struct {
	Success *yim.AckPushRsp
}

var AckPushResult_Success_DEFAULT *yim.AckPushRsp

func (p *AckPushResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AckPushResult) Unmarshal(in []byte) error {
	msg := new(yim.AckPushRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AckPushResult) GetSuccess() *yim.AckPushRsp {
	if !p.IsSetSuccess() {
		return AckPushResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AckPushResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.AckPushRsp)
}

func (p *AckPushResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AckPushResult) GetResult() interface{} {
	return p.Success
}

func revokeMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.RevokeMessageReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).RevokeMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RevokeMessageArgs:
		success, err := handler.(yim.MessageService).RevokeMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RevokeMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRevokeMessageArgs() interface{} {
	return &RevokeMessageArgs{}
}

func newRevokeMessageResult() interface{} {
	return &RevokeMessageResult{}
}

type RevokeMessageArgs struct {
	Req *yim.RevokeMessageReq
}

func (p *RevokeMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RevokeMessageArgs) Unmarshal(in []byte) error {
	msg := new(yim.RevokeMessageReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RevokeMessageArgs_Req_DEFAULT *yim.RevokeMessageReq

func (p *RevokeMessageArgs) GetReq() *yim.RevokeMessageReq {
	if !p.IsSetReq() {
		return RevokeMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RevokeMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RevokeMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RevokeMessageResult struct {
	Success *yim.RevokeMessageRsp
}

var RevokeMessageResult_Success_DEFAULT *yim.RevokeMessageRsp

func (p *RevokeMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RevokeMessageResult) Unmarshal(in []byte) error {
	msg := new(yim.RevokeMessageRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RevokeMessageResult) GetSuccess() *yim.RevokeMessageRsp {
	if !p.IsSetSuccess() {
		return RevokeMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RevokeMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.RevokeMessageRsp)
}

func (p *RevokeMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RevokeMessageResult) GetResult() interface{} {
	return p.Success
}

func markReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.MarkReadReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).MarkRead(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MarkReadArgs:
		success, err := handler.(yim.MessageService).MarkRead(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MarkReadResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMarkReadArgs() interface{} {
	return &MarkReadArgs{}
}

func newMarkReadResult() interface{} {
	return &MarkReadResult{}
}

type MarkReadArgs struct {
	Req *yim.MarkReadReq
}

func (p *MarkReadArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MarkReadArgs) Unmarshal(in []byte) error {
	msg := new(yim.MarkReadReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MarkReadArgs_Req_DEFAULT *yim.MarkReadReq

func (p *MarkReadArgs) GetReq() *yim.MarkReadReq {
	if !p.IsSetReq() {
		return MarkReadArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MarkReadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MarkReadArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MarkReadResult struct {
	Success *yim.MarkReadRsp
}

var MarkReadResult_Success_DEFAULT *yim.MarkReadRsp

func (p *MarkReadResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MarkReadResult) Unmarshal(in []byte) error {
	msg := new(yim.MarkReadRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MarkReadResult) GetSuccess() *yim.MarkReadRsp {
	if !p.IsSetSuccess() {
		return MarkReadResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MarkReadResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.MarkReadRsp)
}

func (p *MarkReadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MarkReadResult) GetResult() interface{} {
	return p.Success
}

func getReadStateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.GetReadStateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).GetReadState(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetReadStateArgs:
		success, err := handler.(yim.MessageService).GetReadState(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetReadStateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetReadStateArgs() interface{} {
	return &GetReadStateArgs{}
}

func newGetReadStateResult() interface{} {
	return &GetReadStateResult{}
}

type GetReadStateArgs struct {
	Req *yim.GetReadStateReq
}

func (p *GetReadStateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetReadStateArgs) Unmarshal(in []byte) error {
	msg := new(yim.GetReadStateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetReadStateArgs_Req_DEFAULT *yim.GetReadStateReq

func (p *GetReadStateArgs) GetReq() *yim.GetReadStateReq {
	if !p.IsSetReq() {
		return GetReadStateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetReadStateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetReadStateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetReadStateResult struct {
	Success *yim.GetReadStateRsp
}

var GetReadStateResult_Success_DEFAULT *yim.GetReadStateRsp

func (p *GetReadStateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetReadStateResult) Unmarshal(in []byte) error {
	msg := new(yim.GetReadStateRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetReadStateResult) GetSuccess() *yim.GetReadStateRsp {
	if !p.IsSetSuccess() {
		return GetReadStateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetReadStateResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.GetReadStateRsp)
}

func (p *GetReadStateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetReadStateResult) GetResult() interface{} {
	return p.Success
}

func listConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.ListConversationsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).ListConversations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListConversationsArgs:
		success, err := handler.(yim.MessageService).ListConversations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListConversationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListConversationsArgs() interface{} {
	return &ListConversationsArgs{}
}

func newListConversationsResult() interface{} {
	return &ListConversationsResult{}
}

type ListConversationsArgs struct {
	Req *yim.ListConversationsReq
}

func (p *ListConversationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListConversationsArgs) Unmarshal(in []byte) error {
	msg := new(yim.ListConversationsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListConversationsArgs_Req_DEFAULT *yim.ListConversationsReq

func (p *ListConversationsArgs) GetReq() *yim.ListConversationsReq {
	if !p.IsSetReq() {
		return ListConversationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListConversationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListConversationsResult struct {
	Success *yim.ListConversationsRsp
}

var ListConversationsResult_Success_DEFAULT *yim.ListConversationsRsp

func (p *ListConversationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListConversationsResult) Unmarshal(in []byte) error {
	msg := new(yim.ListConversationsRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListConversationsResult) GetSuccess() *yim.ListConversationsRsp {
	if !p.IsSetSuccess() {
		return ListConversationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.ListConversationsRsp)
}

func (p *ListConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListConversationsResult) GetResult() interface{} {
	return p.Success
}

func searchMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.SearchMessagesReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).SearchMessages(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchMessagesArgs:
		success, err := handler.(yim.MessageService).SearchMessages(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchMessagesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchMessagesArgs() interface{} {
	return &SearchMessagesArgs{}
}

func newSearchMessagesResult() interface{} {
	return &SearchMessagesResult{}
}

type SearchMessagesArgs struct {
	Req *yim.SearchMessagesReq
}

func (p *SearchMessagesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchMessagesArgs) Unmarshal(in []byte) error {
	msg := new(yim.SearchMessagesReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchMessagesArgs_Req_DEFAULT *yim.SearchMessagesReq

func (p *SearchMessagesArgs) GetReq() *yim.SearchMessagesReq {
	if !p.IsSetReq() {
		return SearchMessagesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchMessagesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchMessagesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchMessagesResult struct {
	Success *yim.SearchMessagesRsp
}

var SearchMessagesResult_Success_DEFAULT *yim.SearchMessagesRsp

func (p *SearchMessagesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchMessagesResult) Unmarshal(in []byte) error {
	msg := new(yim.SearchMessagesRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchMessagesResult) GetSuccess() *yim.SearchMessagesRsp {
	if !p.IsSetSuccess() {
		return SearchMessagesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchMessagesResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.SearchMessagesRsp)
}

func (p *SearchMessagesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchMessagesResult) GetResult() interface{} {
	return p.Success
}

func createConvHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.CreateConvReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.MessageService).CreateConv(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateConvArgs:
		success, err := handler.(yim.MessageService).CreateConv(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateConvResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateConvArgs() interface{} {
	return &CreateConvArgs{}
}

func newCreateConvResult() interface{} {
	return &CreateConvResult{}
}

type CreateConvArgs struct {
	Req *yim.CreateConvReq
}

func (p *CreateConvArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateConvArgs) Unmarshal(in []byte) error {
	msg := new(yim.CreateConvReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateConvArgs_Req_DEFAULT *yim.CreateConvReq

func (p *CreateConvArgs) GetReq() *yim.CreateConvReq {
	if !p.IsSetReq() {
		return CreateConvArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateConvArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateConvArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateConvResult struct {
	Success *yim.CreateConvRsp
}

var CreateConvResult_Success_DEFAULT *yim.CreateConvRsp

func (p *CreateConvResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateConvResult) Unmarshal(in []byte) error {
	msg := new(yim.CreateConvRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateConvResult) GetSuccess() *yim.CreateConvRsp {
	if !p.IsSetSuccess() {
		return CreateConvResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateConvResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.CreateConvRsp)
}

func (p *CreateConvResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateConvResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendMessage(ctx context.Context, Req *yim.SendMessageReq) (r *yim.SendMessageRsp, err error) {
	var _args SendMessageArgs
	_args.Req = Req
	var _result SendMessageResult
	if err = p.c.Call(ctx, "SendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PullHistory(ctx context.Context, Req *yim.PullHistoryReq) (r *yim.PullHistoryRsp, err error) {
	var _args PullHistoryArgs
	_args.Req = Req
	var _result PullHistoryResult
	if err = p.c.Call(ctx, "PullHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Sync(ctx context.Context, Req *yim.SyncReq2) (r *yim.SyncRsp2, err error) {
	var _args SyncArgs
	_args.Req = Req
	var _result SyncResult
	if err = p.c.Call(ctx, "Sync", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AckPush(ctx context.Context, Req *yim.AckPushReq) (r *yim.AckPushRsp, err error) {
	var _args AckPushArgs
	_args.Req = Req
	var _result AckPushResult
	if err = p.c.Call(ctx, "AckPush", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokeMessage(ctx context.Context, Req *yim.RevokeMessageReq) (r *yim.RevokeMessageRsp, err error) {
	var _args RevokeMessageArgs
	_args.Req = Req
	var _result RevokeMessageResult
	if err = p.c.Call(ctx, "RevokeMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkRead(ctx context.Context, Req *yim.MarkReadReq) (r *yim.MarkReadRsp, err error) {
	var _args MarkReadArgs
	_args.Req = Req
	var _result MarkReadResult
	if err = p.c.Call(ctx, "MarkRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetReadState(ctx context.Context, Req *yim.GetReadStateReq) (r *yim.GetReadStateRsp, err error) {
	var _args GetReadStateArgs
	_args.Req = Req
	var _result GetReadStateResult
	if err = p.c.Call(ctx, "GetReadState", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversations(ctx context.Context, Req *yim.ListConversationsReq) (r *yim.ListConversationsRsp, err error) {
	var _args ListConversationsArgs
	_args.Req = Req
	var _result ListConversationsResult
	if err = p.c.Call(ctx, "ListConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchMessages(ctx context.Context, Req *yim.SearchMessagesReq) (r *yim.SearchMessagesRsp, err error) {
	var _args SearchMessagesArgs
	_args.Req = Req
	var _result SearchMessagesResult
	if err = p.c.Call(ctx, "SearchMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateConv(ctx context.Context, Req *yim.CreateConvReq) (r *yim.CreateConvRsp, err error) {
	var _args CreateConvArgs
	_args.Req = Req
	var _result CreateConvResult
	if err = p.c.Call(ctx, "CreateConv", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
