// Code generated by Kitex v0.16.3. DO NOT EDIT.

package cometservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	yim "github.com/yim/kitex_gen/yim"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PushMessage(ctx context.Context, Req *yim.PushMessageReq, callOptions ...callopt.Option) (r *yim.PushMessageRsp, err error)
	Kick(ctx context.Context, Req *yim.KickReq, callOptions ...callopt.Option) (r *yim.KickRsp, err error)
	Drain(ctx context.Context, Req *yim.DrainReq, callOptions ...callopt.Option) (r *yim.DrainRsp, err error)
	Stats(ctx context.Context, Req *yim.CometStatsReq, callOptions ...callopt.Option) (r *yim.CometStatsRsp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCometServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCometServiceClient struct {
	*kClient
}

func (p *kCometServiceClient) PushMessage(ctx context.Context, Req *yim.PushMessageReq, callOptions ...callopt.Option) (r *yim.PushMessageRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushMessage(ctx, Req)
}

func (p *kCometServiceClient) Kick(ctx context.Context, Req *yim.KickReq, callOptions ...callopt.Option) (r *yim.KickRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Kick(ctx, Req)
}

func (p *kCometServiceClient) Drain(ctx context.Context, Req *yim.DrainReq, callOptions ...callopt.Option) (r *yim.DrainRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Drain(ctx, Req)
}

func (p *kCometServiceClient) Stats(ctx context.Context, Req *yim.CometStatsReq, callOptions ...callopt.Option) (r *yim.CometStatsRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Stats(ctx, Req)
}
