// Code generated by Kitex v0.16.3. DO NOT EDIT.

package routerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	yim "github.com/yim/kitex_gen/yim"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetOnlineDevices(ctx context.Context, Req *yim.GetOnlineDevicesReq, callOptions ...callopt.Option) (r *yim.GetOnlineDevicesRsp, err error)
	CleanupInstance(ctx context.Context, Req *yim.CleanupInstanceReq, callOptions ...callopt.Option) (r *yim.CleanupInstanceRsp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRouterServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRouterServiceClient struct {
	*kClient
}

func (p *kRouterServiceClient) GetOnlineDevices(ctx context.Context, Req *yim.GetOnlineDevicesReq, callOptions ...callopt.Option) (r *yim.GetOnlineDevicesRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOnlineDevices(ctx, Req)
}

func (p *kRouterServiceClient) CleanupInstance(ctx context.Context, Req *yim.CleanupInstanceReq, callOptions ...callopt.Option) (r *yim.CleanupInstanceRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CleanupInstance(ctx, Req)
}
