// Code generated by Kitex v0.16.3. DO NOT EDIT.

package routerservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	yim "github.com/yim/kitex_gen/yim"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetOnlineDevices": kitex.NewMethodInfo(
		getOnlineDevicesHandler,
		newGetOnlineDevicesArgs,
		newGetOnlineDevicesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CleanupInstance": kitex.NewMethodInfo(
		cleanupInstanceHandler,
		newCleanupInstanceArgs,
		newCleanupInstanceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	routerServiceServiceInfo                = NewServiceInfo()
	routerServiceServiceInfoForClient       = NewServiceInfoForClient()
	routerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return routerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return routerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return routerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RouterService"
	handlerType := (*yim.RouterService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yim",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func getOnlineDevicesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.GetOnlineDevicesReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RouterService).GetOnlineDevices(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetOnlineDevicesArgs:
		success, err := handler.(yim.RouterService).GetOnlineDevices(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetOnlineDevicesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetOnlineDevicesArgs() interface{} {
	return &GetOnlineDevicesArgs{}
}

func newGetOnlineDevicesResult() interface{} {
	return &GetOnlineDevicesResult{}
}

type GetOnlineDevicesArgs struct {
	Req *yim.GetOnlineDevicesReq
}

func (p *GetOnlineDevicesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetOnlineDevicesArgs) Unmarshal(in []byte) error {
	msg := new(yim.GetOnlineDevicesReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetOnlineDevicesArgs_Req_DEFAULT *yim.GetOnlineDevicesReq

func (p *GetOnlineDevicesArgs) GetReq() *yim.GetOnlineDevicesReq {
	if !p.IsSetReq() {
		return GetOnlineDevicesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetOnlineDevicesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetOnlineDevicesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetOnlineDevicesResult struct {
	Success *yim.GetOnlineDevicesRsp
}

var GetOnlineDevicesResult_Success_DEFAULT *yim.GetOnlineDevicesRsp

func (p *GetOnlineDevicesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetOnlineDevicesResult) Unmarshal(in []byte) error {
	msg := new(yim.GetOnlineDevicesRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetOnlineDevicesResult) GetSuccess() *yim.GetOnlineDevicesRsp {
	if !p.IsSetSuccess() {
		return GetOnlineDevicesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetOnlineDevicesResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.GetOnlineDevicesRsp)
}

func (p *GetOnlineDevicesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetOnlineDevicesResult) GetResult() interface{} {
	return p.Success
}

func cleanupInstanceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.CleanupInstanceReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RouterService).CleanupInstance(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CleanupInstanceArgs:
		success, err := handler.(yim.RouterService).CleanupInstance(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CleanupInstanceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCleanupInstanceArgs() interface{} {
	return &CleanupInstanceArgs{}
}

func newCleanupInstanceResult() interface{} {
	return &CleanupInstanceResult{}
}

type CleanupInstanceArgs struct {
	Req *yim.CleanupInstanceReq
}

func (p *CleanupInstanceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CleanupInstanceArgs) Unmarshal(in []byte) error {
	msg := new(yim.CleanupInstanceReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CleanupInstanceArgs_Req_DEFAULT *yim.CleanupInstanceReq

func (p *CleanupInstanceArgs) GetReq() *yim.CleanupInstanceReq {
	if !p.IsSetReq() {
		return CleanupInstanceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CleanupInstanceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CleanupInstanceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CleanupInstanceResult struct {
	Success *yim.CleanupInstanceRsp
}

var CleanupInstanceResult_Success_DEFAULT *yim.CleanupInstanceRsp

func (p *CleanupInstanceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CleanupInstanceResult) Unmarshal(in []byte) error {
	msg := new(yim.CleanupInstanceRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CleanupInstanceResult) GetSuccess() *yim.CleanupInstanceRsp {
	if !p.IsSetSuccess() {
		return CleanupInstanceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CleanupInstanceResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.CleanupInstanceRsp)
}

func (p *CleanupInstanceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CleanupInstanceResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetOnlineDevices(ctx context.Context, Req *yim.GetOnlineDevicesReq) (r *yim.GetOnlineDevicesRsp, err error) {
	var _args GetOnlineDevicesArgs
	_args.Req = Req
	var _result GetOnlineDevicesResult
	if err = p.c.Call(ctx, "GetOnlineDevices", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CleanupInstance(ctx context.Context, Req *yim.CleanupInstanceReq) (r *yim.CleanupInstanceRsp, err error) {
	var _args CleanupInstanceArgs
	_args.Req = Req
	var _result CleanupInstanceResult
	if err = p.c.Call(ctx, "CleanupInstance", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
