// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: message.proto

package yim

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvType int32

const (
	ConvType_CONV_UNKNOWN ConvType = 0
	ConvType_CONV_SINGLE  ConvType = 1 // 单聊
	ConvType_CONV_GROUP   ConvType = 2 // 群聊
)

// Enum value maps for ConvType.
var (
	ConvType_name = map[int32]string{
		0: "CONV_UNKNOWN",
		1: "CONV_SINGLE",
		2: "CONV_GROUP",
	}
	ConvType_value = map[string]int32{
		"CONV_UNKNOWN": 0,
		"CONV_SINGLE":  1,
		"CONV_GROUP":   2,
	}
)

func (x ConvType) Enum() *ConvType {
	p := new(ConvType)
	*p = x
	return p
}

func (x ConvType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConvType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (ConvType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x ConvType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConvType.Descriptor instead.
func (ConvType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type MsgType int32

const (
	MsgType_MSG_UNKNOWN MsgType = 0
	MsgType_MSG_TEXT    MsgType = 1
	MsgType_MSG_IMAGE   MsgType = 2
	MsgType_MSG_FILE    MsgType = 3
	MsgType_MSG_AUDIO   MsgType = 4
	MsgType_MSG_REVOKE  MsgType = 10 // 撤回: 特殊消息体, 客户端据此更新本地
	MsgType_MSG_SYSTEM  MsgType = 11 // 系统通知(入群/踢人等)
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "MSG_UNKNOWN",
		1:  "MSG_TEXT",
		2:  "MSG_IMAGE",
		3:  "MSG_FILE",
		4:  "MSG_AUDIO",
		10: "MSG_REVOKE",
		11: "MSG_SYSTEM",
	}
	MsgType_value = map[string]int32{
		"MSG_UNKNOWN": 0,
		"MSG_TEXT":    1,
		"MSG_IMAGE":   2,
		"MSG_FILE":    3,
		"MSG_AUDIO":   4,
		"MSG_REVOKE":  10,
		"MSG_SYSTEM":  11,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 发送者视角的消息状态机(仅上行未落库阶段有用, 落库后由 seq 决定)
type SendState int32

const (
	SendState_SEND_UNKNOWN SendState = 0
	SendState_SEND_PENDING SendState = 1 // 已发出未收到 UP_RSP → 时间轮重试
	SendState_SEND_OK      SendState = 2
	SendState_SEND_FAILED  SendState = 3
)

// Enum value maps for SendState.
var (
	SendState_name = map[int32]string{
		0: "SEND_UNKNOWN",
		1: "SEND_PENDING",
		2: "SEND_OK",
		3: "SEND_FAILED",
	}
	SendState_value = map[string]int32{
		"SEND_UNKNOWN": 0,
		"SEND_PENDING": 1,
		"SEND_OK":      2,
		"SEND_FAILED":  3,
	}
)

func (x SendState) Enum() *SendState {
	p := new(SendState)
	*p = x
	return p
}

func (x SendState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendState) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (SendState) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x SendState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendState.Descriptor instead.
func (SendState) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

// conv_id 生成规则: 号段分配 + 嵌入创建者分片基因
// 结构: [1bit标志][41bit时间戳][12bit分片基因][10bit自增]
// 分片基因 = 创建者 uid 对分片数取模 → 关系查询可直路由, 免二次hash
type Conv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId int64    `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Type   ConvType `protobuf:"varint,2,opt,name=type,proto3,enum=yim.ConvType" json:"type,omitempty"`
	// 单聊: 两端 uid, 存储时约定小 uid 在前保证同一单聊唯一
	MemberUids   []int64 `protobuf:"varint,3,rep,packed,name=member_uids,json=memberUids,proto3" json:"member_uids,omitempty"`
	CreateTimeMs int64   `protobuf:"varint,4,opt,name=create_time_ms,json=createTimeMs,proto3" json:"create_time_ms,omitempty"`
	LastSeq      int64   `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"` // 冗余最新 seq, 会话列表免查消息表
	Name         string  `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`                       // 群名 (里程碑11, 单聊空串)
	Avatar       string  `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`                   // 群头像相对 URL (/files/img/...), 单聊空串
}

func (x *Conv) Reset() {
	*x = Conv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conv) ProtoMessage() {}

func (x *Conv) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conv.ProtoReflect.Descriptor instead.
func (*Conv) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Conv) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *Conv) GetType() ConvType {
	if x != nil {
		return x.Type
	}
	return ConvType_CONV_UNKNOWN
}

func (x *Conv) GetMemberUids() []int64 {
	if x != nil {
		return x.MemberUids
	}
	return nil
}

func (x *Conv) GetCreateTimeMs() int64 {
	if x != nil {
		return x.CreateTimeMs
	}
	return 0
}

func (x *Conv) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Conv) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Conv) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type ConvMsgContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=yim.MsgType" json:"type,omitempty"`
	Text string  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// 图片/文件/语音走对象存储客户端直传, 这里只存元数据
	Media *MediaMeta `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	// 撤回/系统类消息的扩展字段
	Ext *Ext `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *ConvMsgContent) Reset() {
	*x = ConvMsgContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvMsgContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvMsgContent) ProtoMessage() {}

func (x *ConvMsgContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvMsgContent.ProtoReflect.Descriptor instead.
func (*ConvMsgContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *ConvMsgContent) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_UNKNOWN
}

func (x *ConvMsgContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConvMsgContent) GetMedia() *MediaMeta {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ConvMsgContent) GetExt() *Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

type MediaMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size       int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Width      int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height     int32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	DurationMs int32  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
}

func (x *MediaMeta) Reset() {
	*x = MediaMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMeta) ProtoMessage() {}

func (x *MediaMeta) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMeta.ProtoReflect.Descriptor instead.
func (*MediaMeta) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *MediaMeta) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaMeta) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaMeta) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaMeta) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Ext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefMsgId int64  `protobuf:"varint,1,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"` // 撤回/回复的目标消息
	OpUid    int64  `protobuf:"varint,2,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`            // 操作者
	Json     string `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`                            // 兜底扩展, 优先走强类型字段
	RefText  string `protobuf:"bytes,4,opt,name=ref_text,json=refText,proto3" json:"ref_text,omitempty"`       // 回复引用的预览文本快照 (原消息可能已不在拉取窗口内)
}

func (x *Ext) Reset() {
	*x = Ext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ext) ProtoMessage() {}

func (x *Ext) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ext.ProtoReflect.Descriptor instead.
func (*Ext) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *Ext) GetRefMsgId() int64 {
	if x != nil {
		return x.RefMsgId
	}
	return 0
}

func (x *Ext) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *Ext) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *Ext) GetRefText() string {
	if x != nil {
		return x.RefText
	}
	return ""
}

// 存储行结构(服务端内部/同步响应共用)
type ConvMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId        int64           `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId       int64           `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	FromUid      int64           `protobuf:"varint,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	Seq          int64           `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	ServerTimeMs int64           `protobuf:"varint,5,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	Content      *ConvMsgContent `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ConvMessage) Reset() {
	*x = ConvMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvMessage) ProtoMessage() {}

func (x *ConvMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvMessage.ProtoReflect.Descriptor instead.
func (*ConvMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ConvMessage) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ConvMessage) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ConvMessage) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *ConvMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ConvMessage) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *ConvMessage) GetContent() *ConvMsgContent {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x79, 0x69, 0x6d, 0x22, 0xd0, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x76, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x69, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x76,
	0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x24, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x1a, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x78, 0x74, 0x52, 0x03, 0x65,
	0x78, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0x69, 0x0a, 0x03, 0x45, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x0a,
	0x72, 0x65, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x72, 0x65, 0x66, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70,
	0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x70, 0x55, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x5f, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x66, 0x54, 0x65, 0x78, 0x74,
	0x22, 0xbf, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x24, 0x0a,
	0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x4d, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x4d,
	0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2a, 0x3d, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x4f, 0x4e, 0x56, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4e, 0x56, 0x5f, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x56, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10,
	0x02, 0x2a, 0x74, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b,
	0x4d, 0x53, 0x47, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x53, 0x47, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x53,
	0x47, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x53, 0x47, 0x5f,
	0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x53, 0x47, 0x5f, 0x52,
	0x45, 0x56, 0x4f, 0x4b, 0x45, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x53, 0x47, 0x5f, 0x53,
	0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x0b, 0x2a, 0x4d, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x50,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x4e, 0x44,
	0x5f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6d, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x79, 0x69, 0x6d, 0x3b, 0x79, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_proto_goTypes = []interface{}{
	(ConvType)(0),          // 0: yim.ConvType
	(MsgType)(0),           // 1: yim.MsgType
	(SendState)(0),         // 2: yim.SendState
	(*Conv)(nil),           // 3: yim.Conv
	(*ConvMsgContent)(nil), // 4: yim.ConvMsgContent
	(*MediaMeta)(nil),      // 5: yim.MediaMeta
	(*Ext)(nil),            // 6: yim.Ext
	(*ConvMessage)(nil),    // 7: yim.ConvMessage
}
var file_message_proto_depIdxs = []int32{
	0, // 0: yim.Conv.type:type_name -> yim.ConvType
	1, // 1: yim.ConvMsgContent.type:type_name -> yim.MsgType
	5, // 2: yim.ConvMsgContent.media:type_name -> yim.MediaMeta
	6, // 3: yim.ConvMsgContent.ext:type_name -> yim.Ext
	4, // 4: yim.ConvMessage.content:type_name -> yim.ConvMsgContent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvMsgContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}

var _ context.Context
