// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: protocol.proto

package yim

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_CMD_UNKNOWN Command = 0
	// 连接生命周期
	Command_CMD_CONNECT     Command = 1 // C→S 握手(第一帧), 携带设备信息
	Command_CMD_CONNECT_RSP Command = 2 // S→C 握手应答, 失败则服务端直接断开
	Command_CMD_HEARTBEAT   Command = 3 // 双向保活, 30s 间隔, 连续 3 次超时判死
	Command_CMD_KICK        Command = 4 // S→C 多端互踢/强制下线, 收到后禁止重连同一 token
	Command_CMD_DISCONNECT  Command = 5 // S→C 服务端主动断开前的通知(发布排水)
	// 消息收发 (推拉结合: 推送只带轻通知, 不带消息体)
	Command_CMD_MESSAGE_UP     Command = 10 // C→S 上行消息
	Command_CMD_MESSAGE_UP_RSP Command = 11 // S→C 上行确认(服务端已落库, 返回服务端 seq)
	Command_CMD_MESSAGE_PUSH   Command = 12 // S→C 轻通知: 仅 conv_id + max_seq
	Command_CMD_ACK            Command = 13 // 双向逐条确认 (对 UP_RSP/PUSH 的确认)
	// 同步 (断线重连/唤醒/发现缺号时)
	Command_CMD_SYNC     Command = 14 // C→S: 携带各会话本地 last_seq, 拉增量
	Command_CMD_SYNC_RSP Command = 15 // S→C: 增量消息列表
	// 业务事件通知 (里程碑10): 好友/群/在线状态的"推"侧。
	// 推保证实时, 拉保证可靠 —— 事件可丢可重, 客户端收到后局部重拉。
	Command_CMD_EVENT  Command = 16 // S→C: EventFrame (好友申请/同意/删除/群变更/在线)
	Command_CMD_TYPING Command = 17 // C→S: 输入中提示 (里程碑12, 即发即弃不落库)
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0:  "CMD_UNKNOWN",
		1:  "CMD_CONNECT",
		2:  "CMD_CONNECT_RSP",
		3:  "CMD_HEARTBEAT",
		4:  "CMD_KICK",
		5:  "CMD_DISCONNECT",
		10: "CMD_MESSAGE_UP",
		11: "CMD_MESSAGE_UP_RSP",
		12: "CMD_MESSAGE_PUSH",
		13: "CMD_ACK",
		14: "CMD_SYNC",
		15: "CMD_SYNC_RSP",
		16: "CMD_EVENT",
		17: "CMD_TYPING",
	}
	Command_value = map[string]int32{
		"CMD_UNKNOWN":        0,
		"CMD_CONNECT":        1,
		"CMD_CONNECT_RSP":    2,
		"CMD_HEARTBEAT":      3,
		"CMD_KICK":           4,
		"CMD_DISCONNECT":     5,
		"CMD_MESSAGE_UP":     10,
		"CMD_MESSAGE_UP_RSP": 11,
		"CMD_MESSAGE_PUSH":   12,
		"CMD_ACK":            13,
		"CMD_SYNC":           14,
		"CMD_SYNC_RSP":       15,
		"CMD_EVENT":          16,
		"CMD_TYPING":         17,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

type AckTarget int32

const (
	AckTarget_ACK_UNKNOWN  AckTarget = 0
	AckTarget_ACK_FOR_UP   AckTarget = 1 // 客户端确认上行回执
	AckTarget_ACK_FOR_PUSH AckTarget = 2 // 客户端确认下行推送 → 服务端时间轮取消定时
)

// Enum value maps for AckTarget.
var (
	AckTarget_name = map[int32]string{
		0: "ACK_UNKNOWN",
		1: "ACK_FOR_UP",
		2: "ACK_FOR_PUSH",
	}
	AckTarget_value = map[string]int32{
		"ACK_UNKNOWN":  0,
		"ACK_FOR_UP":   1,
		"ACK_FOR_PUSH": 2,
	}
)

func (x AckTarget) Enum() *AckTarget {
	p := new(AckTarget)
	*p = x
	return p
}

func (x AckTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[1].Descriptor()
}

func (AckTarget) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[1]
}

func (x AckTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckTarget.Descriptor instead.
func (AckTarget) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

// 连接级统一信封
type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameId uint32  `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"` // 客户端自增, 用于请求响应配对
	Cmd     Command `protobuf:"varint,2,opt,name=cmd,proto3,enum=yim.Command" json:"cmd,omitempty"`
	Error   *Error  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // 非零时 body 可能无意义
	// Types that are assignable to Payload:
	//
	//	*Frame_Connect
	//	*Frame_ConnectRsp
	//	*Frame_Heartbeat
	//	*Frame_Kick
	//	*Frame_Disconnect
	//	*Frame_MessageUp
	//	*Frame_MessageUpRsp
	//	*Frame_MessagePush
	//	*Frame_Ack
	//	*Frame_Sync
	//	*Frame_SyncRsp
	//	*Frame_Event
	//	*Frame_Typing
	Payload isFrame_Payload `protobuf_oneof:"payload"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetFrameId() uint32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *Frame) GetCmd() Command {
	if x != nil {
		return x.Cmd
	}
	return Command_CMD_UNKNOWN
}

func (x *Frame) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (m *Frame) GetPayload() isFrame_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Frame) GetConnect() *ConnectReq {
	if x, ok := x.GetPayload().(*Frame_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *Frame) GetConnectRsp() *ConnectRsp {
	if x, ok := x.GetPayload().(*Frame_ConnectRsp); ok {
		return x.ConnectRsp
	}
	return nil
}

func (x *Frame) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetPayload().(*Frame_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *Frame) GetKick() *Kick {
	if x, ok := x.GetPayload().(*Frame_Kick); ok {
		return x.Kick
	}
	return nil
}

func (x *Frame) GetDisconnect() *Disconnect {
	if x, ok := x.GetPayload().(*Frame_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

func (x *Frame) GetMessageUp() *MessageUpReq {
	if x, ok := x.GetPayload().(*Frame_MessageUp); ok {
		return x.MessageUp
	}
	return nil
}

func (x *Frame) GetMessageUpRsp() *MessageUpRsp {
	if x, ok := x.GetPayload().(*Frame_MessageUpRsp); ok {
		return x.MessageUpRsp
	}
	return nil
}

func (x *Frame) GetMessagePush() *MessagePush {
	if x, ok := x.GetPayload().(*Frame_MessagePush); ok {
		return x.MessagePush
	}
	return nil
}

func (x *Frame) GetAck() *Ack {
	if x, ok := x.GetPayload().(*Frame_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *Frame) GetSync() *SyncReq {
	if x, ok := x.GetPayload().(*Frame_Sync); ok {
		return x.Sync
	}
	return nil
}

func (x *Frame) GetSyncRsp() *SyncRsp {
	if x, ok := x.GetPayload().(*Frame_SyncRsp); ok {
		return x.SyncRsp
	}
	return nil
}

func (x *Frame) GetEvent() *EventFrame {
	if x, ok := x.GetPayload().(*Frame_Event); ok {
		return x.Event
	}
	return nil
}

func (x *Frame) GetTyping() *Typing {
	if x, ok := x.GetPayload().(*Frame_Typing); ok {
		return x.Typing
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Connect struct {
	Connect *ConnectReq `protobuf:"bytes,10,opt,name=connect,proto3,oneof"`
}

type Frame_ConnectRsp struct {
	ConnectRsp *ConnectRsp `protobuf:"bytes,11,opt,name=connect_rsp,json=connectRsp,proto3,oneof"`
}

type Frame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type Frame_Kick struct {
	Kick *Kick `protobuf:"bytes,13,opt,name=kick,proto3,oneof"`
}

type Frame_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,14,opt,name=disconnect,proto3,oneof"`
}

type Frame_MessageUp struct {
	MessageUp *MessageUpReq `protobuf:"bytes,20,opt,name=message_up,json=messageUp,proto3,oneof"`
}

type Frame_MessageUpRsp struct {
	MessageUpRsp *MessageUpRsp `protobuf:"bytes,21,opt,name=message_up_rsp,json=messageUpRsp,proto3,oneof"`
}

type Frame_MessagePush struct {
	MessagePush *MessagePush `protobuf:"bytes,22,opt,name=message_push,json=messagePush,proto3,oneof"`
}

type Frame_Ack struct {
	Ack *Ack `protobuf:"bytes,23,opt,name=ack,proto3,oneof"`
}

type Frame_Sync struct {
	Sync *SyncReq `protobuf:"bytes,24,opt,name=sync,proto3,oneof"`
}

type Frame_SyncRsp struct {
	SyncRsp *SyncRsp `protobuf:"bytes,25,opt,name=sync_rsp,json=syncRsp,proto3,oneof"`
}

type Frame_Event struct {
	Event *EventFrame `protobuf:"bytes,26,opt,name=event,proto3,oneof"`
}

type Frame_Typing struct {
	Typing *Typing `protobuf:"bytes,27,opt,name=typing,proto3,oneof"`
}

func (*Frame_Connect) isFrame_Payload() {}

func (*Frame_ConnectRsp) isFrame_Payload() {}

func (*Frame_Heartbeat) isFrame_Payload() {}

func (*Frame_Kick) isFrame_Payload() {}

func (*Frame_Disconnect) isFrame_Payload() {}

func (*Frame_MessageUp) isFrame_Payload() {}

func (*Frame_MessageUpRsp) isFrame_Payload() {}

func (*Frame_MessagePush) isFrame_Payload() {}

func (*Frame_Ack) isFrame_Payload() {}

func (*Frame_Sync) isFrame_Payload() {}

func (*Frame_SyncRsp) isFrame_Payload() {}

func (*Frame_Event) isFrame_Payload() {}

func (*Frame_Typing) isFrame_Payload() {}

type ConnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`   // HTTP 登录时签发的 JWT, Comet 只转发校验
	Device *DeviceInfo `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"` // Comet 校验后写路由表 uid:device → 本实例
}

func (x *ConnectReq) Reset() {
	*x = ConnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReq) ProtoMessage() {}

func (x *ConnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReq.ProtoReflect.Descriptor instead.
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnectReq) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

type ConnectRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTimeMs int64 `protobuf:"varint,1,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"` // 客户端时钟校准用
	// 用户级变更序号快照: 客户端若落后则立即发起 SYNC
	UserSyncSeq int64 `protobuf:"varint,2,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"`
}

func (x *ConnectRsp) Reset() {
	*x = ConnectRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRsp) ProtoMessage() {}

func (x *ConnectRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRsp.ProtoReflect.Descriptor instead.
func (*ConnectRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRsp) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *ConnectRsp) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 携带上行流水水位, 便于服务端检测客户端丢包/假活
	LastFrameId uint64 `protobuf:"varint,1,opt,name=last_frame_id,json=lastFrameId,proto3" json:"last_frame_id,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetLastFrameId() uint64 {
	if x != nil {
		return x.LastFrameId
	}
	return 0
}

type Kick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason      string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`                                 // "multi_device_conflict" / "token_invalidated"
	UserSyncSeq int64  `protobuf:"varint,2,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"` // 被踢端最后同步水位, 重新登录后续传
}

func (x *Kick) Reset() {
	*x = Kick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *Kick) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Kick) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

type Disconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason       string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // "server_maintenance" → 客户端立即重连其他实例
	RetryAfterMs int32  `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *Disconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Disconnect) GetRetryAfterMs() int32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type MessageUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgId uint64          `protobuf:"varint,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端生成的雪花ID, 幂等键(布隆粗筛+Redis精查)
	ConvId      int64           `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Content     *ConvMsgContent `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MessageUpReq) Reset() {
	*x = MessageUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpReq) ProtoMessage() {}

func (x *MessageUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpReq.ProtoReflect.Descriptor instead.
func (*MessageUpReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *MessageUpReq) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *MessageUpReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *MessageUpReq) GetContent() *ConvMsgContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type MessageUpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgId  uint64 `protobuf:"varint,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MsgId        int64  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 服务端分布式ID(号段)
	Seq          int64  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`                  // 会话内单调 seq, 客户端此后以此排序
	ServerTimeMs int64  `protobuf:"varint,4,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
}

func (x *MessageUpRsp) Reset() {
	*x = MessageUpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpRsp) ProtoMessage() {}

func (x *MessageUpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpRsp.ProtoReflect.Descriptor instead.
func (*MessageUpRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *MessageUpRsp) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *MessageUpRsp) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageUpRsp) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageUpRsp) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

// 轻通知: 不含消息体。客户端发现本地 seq < max_seq 时发 SYNC 拉取。
// 设计依据: 推送可丢可重, 丢失由 SYNC 补齐 —— 推保证实时, 拉保证可靠。
type MessagePush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MaxSeq int64 `protobuf:"varint,2,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	// 群聊时发送者 uid, 用于客户端决定是否拉取(可按免打扰跳过)
	FromUid     int64 `protobuf:"varint,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	UserSyncSeq int64 `protobuf:"varint,4,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"`
}

func (x *MessagePush) Reset() {
	*x = MessagePush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePush) ProtoMessage() {}

func (x *MessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePush.ProtoReflect.Descriptor instead.
func (*MessagePush) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *MessagePush) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *MessagePush) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *MessagePush) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *MessagePush) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId      int64     `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	AckSeq      int64     `protobuf:"varint,2,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`                  // 累积确认: <=ack_seq 全部已收到
	ClientMsgId uint64    `protobuf:"varint,3,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 上行确认时回填
	Target      AckTarget `protobuf:"varint,4,opt,name=target,proto3,enum=yim.AckTarget" json:"target,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *Ack) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *Ack) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *Ack) GetTarget() AckTarget {
	if x != nil {
		return x.Target
	}
	return AckTarget_ACK_UNKNOWN
}

type SyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户级水位: ConnectRsp 下发的 user_sync_seq
	UserSyncSeq int64 `protobuf:"varint,1,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"`
	// 客户端已知的各会话水位, 服务端按差集算增量
	// (只传有本地数据的会话, 新设备不传 = 全量同步)
	Watermarks []*ConvWatermark `protobuf:"bytes,2,rep,name=watermarks,proto3" json:"watermarks,omitempty"`
}

func (x *SyncReq) Reset() {
	*x = SyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReq) ProtoMessage() {}

func (x *SyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReq.ProtoReflect.Descriptor instead.
func (*SyncReq) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *SyncReq) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

func (x *SyncReq) GetWatermarks() []*ConvWatermark {
	if x != nil {
		return x.Watermarks
	}
	return nil
}

type ConvWatermark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId  int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	LastSeq int64 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
}

func (x *ConvWatermark) Reset() {
	*x = ConvWatermark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvWatermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvWatermark) ProtoMessage() {}

func (x *ConvWatermark) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvWatermark.ProtoReflect.Descriptor instead.
func (*ConvWatermark) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *ConvWatermark) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ConvWatermark) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type SyncRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSyncSeq int64          `protobuf:"varint,1,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"` // 同步后的新水位
	Messages    []*ConvMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`                             // 按 conv_id 分组的增量
	// 增量过大的会话只返回水位, 客户端走分页历史拉取
	Overflow []*ConvWatermark `protobuf:"bytes,3,rep,name=overflow,proto3" json:"overflow,omitempty"`
}

func (x *SyncRsp) Reset() {
	*x = SyncRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRsp) ProtoMessage() {}

func (x *SyncRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRsp.ProtoReflect.Descriptor instead.
func (*SyncRsp) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *SyncRsp) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

func (x *SyncRsp) GetMessages() []*ConvMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncRsp) GetOverflow() []*ConvWatermark {
	if x != nil {
		return x.Overflow
	}
	return nil
}

// S→C 业务事件通知: 客户端按 type 局部重拉对应列表 (事件不带业务全量数据)。
type EventFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                    // FRIEND_REQUEST / FRIEND_HANDLED / FRIEND_DELETED / GROUP_CHANGED / PRESENCE
	Uid    int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                     // 事件主体: 申请人 / 处理人 / 操作者 / 状态变更者
	ConvId int64  `protobuf:"varint,3,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"` // 群类事件的会话 id
	Online bool   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`               // PRESENCE: true=上线
	Seq    int64  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`                     // READ 回执: 对方已读到的 seq (里程碑12)
}

func (x *EventFrame) Reset() {
	*x = EventFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFrame) ProtoMessage() {}

func (x *EventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFrame.ProtoReflect.Descriptor instead.
func (*EventFrame) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *EventFrame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventFrame) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EventFrame) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *EventFrame) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *EventFrame) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 输入中 (里程碑12): C→S 只带会话, from_uid 以连接身份为准; 服务端经
// Redis ephemeral 通道扇出给会话其他成员, 即发即弃不落库。
type Typing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
}

func (x *Typing) Reset() {
	*x = Typing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Typing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Typing) ProtoMessage() {}

func (x *Typing) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Typing.ProtoReflect.Descriptor instead.
func (*Typing) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *Typing) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

// Kafka yim.relation.event 事件体。
//
//	关系域事件: relation svc 直发 (targets = 应通知的用户)
//	在线事件:   comet 发原始 PRESENCE (targets 空) → relation 补齐好友列表再发回本 topic
//
// comet 每实例全量消费本 topic, 按 targets 过滤本地在线连接推送 (事件量级低, 无需分区路由)。
type RelationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event   *EventFrame `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Targets []int64     `protobuf:"varint,2,rep,packed,name=targets,proto3" json:"targets,omitempty"`
}

func (x *RelationEvent) Reset() {
	*x = RelationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationEvent) ProtoMessage() {}

func (x *RelationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationEvent.ProtoReflect.Descriptor instead.
func (*RelationEvent) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *RelationEvent) GetEvent() *EventFrame {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RelationEvent) GetTargets() []int64 {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_protocol_proto protoreflect.FileDescriptor

var file_protocol_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x79, 0x69, 0x6d, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb7, 0x05, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x79, 0x69, 0x6d,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x73, 0x70, 0x48, 0x00, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x09, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x79, 0x69, 0x6d, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48, 0x00, 0x52,
	0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6b, 0x69,
	0x63, 0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4b,
	0x69, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x63, 0x6b, 0x12, 0x31, 0x0a, 0x0a, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x32,
	0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x70, 0x18, 0x14, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x55, 0x70, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x55, 0x70, 0x12, 0x39, 0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x70,
	0x5f, 0x72, 0x73, 0x70, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x79, 0x69, 0x6d,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x70, 0x52, 0x73, 0x70, 0x48, 0x00, 0x52,
	0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x70, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a,
	0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x18, 0x16, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x48, 0x00, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x50, 0x75, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x17, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61,
	0x63, 0x6b, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x48, 0x00,
	0x52, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x29, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x72,
	0x73, 0x70, 0x18, 0x19, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x73, 0x70, 0x48, 0x00, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x73,
	0x70, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x74, 0x79,
	0x70, 0x69, 0x6e, 0x67, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x79, 0x69, 0x6d,
	0x2e, 0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x06, 0x74, 0x79, 0x70, 0x69, 0x6e,
	0x67, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4b, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x27, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x56, 0x0a, 0x0a, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x22, 0x0a,
	0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65,
	0x71, 0x22, 0x2f, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x22,
	0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x42, 0x0a, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f,
	0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x22, 0x4a, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e,
	0x72, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x74, 0x72, 0x79, 0x41, 0x66, 0x74, 0x65, 0x72,
	0x4d, 0x73, 0x22, 0x7a, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x70, 0x52,
	0x65, 0x71, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12,
	0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x73, 0x67, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x81,
	0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x70, 0x52, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x4d, 0x73, 0x22, 0x7e, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x75, 0x73,
	0x68, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61,
	0x78, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x78,
	0x53, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x65, 0x71, 0x22, 0x83, 0x01, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x76, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x41, 0x63, 0x6b, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x61, 0x0a, 0x07, 0x53, 0x79, 0x6e, 0x63,
	0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x0a, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x52,
	0x0a, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x22, 0x43, 0x0a, 0x0d, 0x43,
	0x6f, 0x6e, 0x76, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x71,
	0x22, 0x8b, 0x01, 0x0a, 0x07, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0d,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71,
	0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x57, 0x61, 0x74, 0x65, 0x72,
	0x6d, 0x61, 0x72, 0x6b, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0x75,
	0x0a, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x21, 0x0a, 0x06, 0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x2a, 0x83, 0x02, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4d, 0x44, 0x5f, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4d, 0x44, 0x5f,
	0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x4d, 0x44, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x03,
	0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4d, 0x44, 0x5f, 0x4b, 0x49, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x12,
	0x0a, 0x0e, 0x43, 0x4d, 0x44, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54,
	0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4d, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x5f, 0x55, 0x50, 0x10, 0x0a, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4d, 0x44, 0x5f, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x50, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x0b, 0x12, 0x14,
	0x0a, 0x10, 0x43, 0x4d, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x50, 0x55,
	0x53, 0x48, 0x10, 0x0c, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4d, 0x44, 0x5f, 0x41, 0x43, 0x4b, 0x10,
	0x0d, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4d, 0x44, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x0e, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x4d, 0x44, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x5f, 0x52, 0x53, 0x50, 0x10,
	0x0f, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4d, 0x44, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x10,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4d, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x11,
	0x2a, 0x3e, 0x0a, 0x09, 0x41, 0x63, 0x6b, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x43, 0x4b, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x41, 0x43, 0x4b, 0x5f, 0x46, 0x4f, 0x52, 0x5f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x41, 0x43, 0x4b, 0x5f, 0x46, 0x4f, 0x52, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x10, 0x02,
	0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79,
	0x69, 0x6d, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x79, 0x69, 0x6d,
	0x3b, 0x79, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData = file_protocol_proto_rawDesc
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proto_rawDescData)
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protocol_proto_goTypes = []interface{}{
	(Command)(0),           // 0: yim.Command
	(AckTarget)(0),         // 1: yim.AckTarget
	(*Frame)(nil),          // 2: yim.Frame
	(*ConnectReq)(nil),     // 3: yim.ConnectReq
	(*ConnectRsp)(nil),     // 4: yim.ConnectRsp
	(*Heartbeat)(nil),      // 5: yim.Heartbeat
	(*Kick)(nil),           // 6: yim.Kick
	(*Disconnect)(nil),     // 7: yim.Disconnect
	(*MessageUpReq)(nil),   // 8: yim.MessageUpReq
	(*MessageUpRsp)(nil),   // 9: yim.MessageUpRsp
	(*MessagePush)(nil),    // 10: yim.MessagePush
	(*Ack)(nil),            // 11: yim.Ack
	(*SyncReq)(nil),        // 12: yim.SyncReq
	(*ConvWatermark)(nil),  // 13: yim.ConvWatermark
	(*SyncRsp)(nil),        // 14: yim.SyncRsp
	(*EventFrame)(nil),     // 15: yim.EventFrame
	(*Typing)(nil),         // 16: yim.Typing
	(*RelationEvent)(nil),  // 17: yim.RelationEvent
	(*Error)(nil),          // 18: yim.Error
	(*DeviceInfo)(nil),     // 19: yim.DeviceInfo
	(*ConvMsgContent)(nil), // 20: yim.ConvMsgContent
	(*ConvMessage)(nil),    // 21: yim.ConvMessage
}
var file_protocol_proto_depIdxs = []int32{
	0,  // 0: yim.Frame.cmd:type_name -> yim.Command
	18, // 1: yim.Frame.error:type_name -> yim.Error
	3,  // 2: yim.Frame.connect:type_name -> yim.ConnectReq
	4,  // 3: yim.Frame.connect_rsp:type_name -> yim.ConnectRsp
	5,  // 4: yim.Frame.heartbeat:type_name -> yim.Heartbeat
	6,  // 5: yim.Frame.kick:type_name -> yim.Kick
	7,  // 6: yim.Frame.disconnect:type_name -> yim.Disconnect
	8,  // 7: yim.Frame.message_up:type_name -> yim.MessageUpReq
	9,  // 8: yim.Frame.message_up_rsp:type_name -> yim.MessageUpRsp
	10, // 9: yim.Frame.message_push:type_name -> yim.MessagePush
	11, // 10: yim.Frame.ack:type_name -> yim.Ack
	12, // 11: yim.Frame.sync:type_name -> yim.SyncReq
	14, // 12: yim.Frame.sync_rsp:type_name -> yim.SyncRsp
	15, // 13: yim.Frame.event:type_name -> yim.EventFrame
	16, // 14: yim.Frame.typing:type_name -> yim.Typing
	19, // 15: yim.ConnectReq.device:type_name -> yim.DeviceInfo
	20, // 16: yim.MessageUpReq.content:type_name -> yim.ConvMsgContent
	1,  // 17: yim.Ack.target:type_name -> yim.AckTarget
	13, // 18: yim.SyncReq.watermarks:type_name -> yim.ConvWatermark
	21, // 19: yim.SyncRsp.messages:type_name -> yim.ConvMessage
	13, // 20: yim.SyncRsp.overflow:type_name -> yim.ConvWatermark
	15, // 21: yim.RelationEvent.event:type_name -> yim.EventFrame
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	file_common_proto_init()
	file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvWatermark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Typing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Frame_Connect)(nil),
		(*Frame_ConnectRsp)(nil),
		(*Frame_Heartbeat)(nil),
		(*Frame_Kick)(nil),
		(*Frame_Disconnect)(nil),
		(*Frame_MessageUp)(nil),
		(*Frame_MessageUpRsp)(nil),
		(*Frame_MessagePush)(nil),
		(*Frame_Ack)(nil),
		(*Frame_Sync)(nil),
		(*Frame_SyncRsp)(nil),
		(*Frame_Event)(nil),
		(*Frame_Typing)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_rawDesc = nil
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}

var _ context.Context
