// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: service_message.proto

package yim

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullMode int32

const (
	PullMode_PULL_UNKNOWN       PullMode = 0
	PullMode_PULL_SEQ_RANGE     PullMode = 1
	PullMode_PULL_PAGE_BACKWARD PullMode = 2
)

// Enum value maps for PullMode.
var (
	PullMode_name = map[int32]string{
		0: "PULL_UNKNOWN",
		1: "PULL_SEQ_RANGE",
		2: "PULL_PAGE_BACKWARD",
	}
	PullMode_value = map[string]int32{
		"PULL_UNKNOWN":       0,
		"PULL_SEQ_RANGE":     1,
		"PULL_PAGE_BACKWARD": 2,
	}
)

func (x PullMode) Enum() *PullMode {
	p := new(PullMode)
	*p = x
	return p
}

func (x PullMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullMode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_message_proto_enumTypes[0].Descriptor()
}

func (PullMode) Type() protoreflect.EnumType {
	return &file_service_message_proto_enumTypes[0]
}

func (x PullMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullMode.Descriptor instead.
func (PullMode) EnumDescriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{0}
}

type SendMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMsgId uint64          `protobuf:"varint,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ConvId      int64           `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	FromUid     int64           `protobuf:"varint,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"` // Comet 已鉴权, from_uid 不信任客户端原始请求
	Content     *ConvMsgContent `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageReq) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *SendMessageReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *SendMessageReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *SendMessageReq) GetContent() *ConvMsgContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendMessageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId        int64  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq          int64  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ServerTimeMs int64  `protobuf:"varint,3,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	Error        *Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // 幂等命中时返回已存在的 msg_id/seq, 不视为错误
}

func (x *SendMessageRsp) Reset() {
	*x = SendMessageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRsp) ProtoMessage() {}

func (x *SendMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRsp.ProtoReflect.Descriptor instead.
func (*SendMessageRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRsp) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageRsp) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageRsp) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *SendMessageRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type PullHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	// 二选一: 按 seq 精确拉段, 或倒序分页
	Mode      PullMode `protobuf:"varint,2,opt,name=mode,proto3,enum=yim.PullMode" json:"mode,omitempty"`
	FromSeq   int64    `protobuf:"varint,3,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // mode=SEQ_RANGE 时生效, [from_seq, to_seq]
	ToSeq     int64    `protobuf:"varint,4,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"`
	BeforeSeq int64    `protobuf:"varint,5,opt,name=before_seq,json=beforeSeq,proto3" json:"before_seq,omitempty"` // mode=PAGE_BACKWARD 时生效, 取 < before_seq 的
	Limit     int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`                          // 服务端 clamp 至 100
	OpUid     int64    `protobuf:"varint,7,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`             // 发起者 (里程碑9 成员校验: 非会话成员拒绝, 防越权读)
}

func (x *PullHistoryReq) Reset() {
	*x = PullHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullHistoryReq) ProtoMessage() {}

func (x *PullHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullHistoryReq.ProtoReflect.Descriptor instead.
func (*PullHistoryReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{2}
}

func (x *PullHistoryReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *PullHistoryReq) GetMode() PullMode {
	if x != nil {
		return x.Mode
	}
	return PullMode_PULL_UNKNOWN
}

func (x *PullHistoryReq) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *PullHistoryReq) GetToSeq() int64 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

func (x *PullHistoryReq) GetBeforeSeq() int64 {
	if x != nil {
		return x.BeforeSeq
	}
	return 0
}

func (x *PullHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PullHistoryReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

type PullHistoryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*ConvMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore  bool           `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // PULL_PAGE_BACKWARD 时指示还有更早的
	MinSeq   int64          `protobuf:"varint,3,opt,name=min_seq,json=minSeq,proto3" json:"min_seq,omitempty"`    // 本会话最老消息 seq, 客户端判断能否继续翻页
	Error    *Error         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                     // 业务错误 (里程碑9: op_uid 非会话成员 code 25)
}

func (x *PullHistoryRsp) Reset() {
	*x = PullHistoryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullHistoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullHistoryRsp) ProtoMessage() {}

func (x *PullHistoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullHistoryRsp.ProtoReflect.Descriptor instead.
func (*PullHistoryRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{3}
}

func (x *PullHistoryRsp) GetMessages() []*ConvMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PullHistoryRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *PullHistoryRsp) GetMinSeq() int64 {
	if x != nil {
		return x.MinSeq
	}
	return 0
}

func (x *PullHistoryRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// SyncReq2/SyncRsp2: 与 protocol.proto 的 SYNC 指令 body 同构,
// 但作为 gRPC 接口服务端可返回更多信息(overflow 等)
type SyncReq2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         int64            `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserSyncSeq int64            `protobuf:"varint,2,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"`
	Watermarks  []*ConvWatermark `protobuf:"bytes,3,rep,name=watermarks,proto3" json:"watermarks,omitempty"`
}

func (x *SyncReq2) Reset() {
	*x = SyncReq2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReq2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReq2) ProtoMessage() {}

func (x *SyncReq2) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReq2.ProtoReflect.Descriptor instead.
func (*SyncReq2) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{4}
}

func (x *SyncReq2) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SyncReq2) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

func (x *SyncReq2) GetWatermarks() []*ConvWatermark {
	if x != nil {
		return x.Watermarks
	}
	return nil
}

type SyncRsp2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSyncSeq int64            `protobuf:"varint,1,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"`
	Messages    []*ConvMessage   `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Overflow    []*ConvWatermark `protobuf:"bytes,3,rep,name=overflow,proto3" json:"overflow,omitempty"`
}

func (x *SyncRsp2) Reset() {
	*x = SyncRsp2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRsp2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRsp2) ProtoMessage() {}

func (x *SyncRsp2) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRsp2.ProtoReflect.Descriptor instead.
func (*SyncRsp2) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{5}
}

func (x *SyncRsp2) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

func (x *SyncRsp2) GetMessages() []*ConvMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncRsp2) GetOverflow() []*ConvWatermark {
	if x != nil {
		return x.Overflow
	}
	return nil
}

type AckPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 确认者 (接收端)
	ConvId int64 `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	AckSeq int64 `protobuf:"varint,3,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"` // 累积确认: conv 内 <= ack_seq 的待确认推送全部完成
}

func (x *AckPushReq) Reset() {
	*x = AckPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPushReq) ProtoMessage() {}

func (x *AckPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPushReq.ProtoReflect.Descriptor instead.
func (*AckPushReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{6}
}

func (x *AckPushReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AckPushReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *AckPushReq) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

type AckPushRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AckPushRsp) Reset() {
	*x = AckPushRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckPushRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPushRsp) ProtoMessage() {}

func (x *AckPushRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPushRsp.ProtoReflect.Descriptor instead.
func (*AckPushRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{7}
}

type RevokeMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId  int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId int64 `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	OpUid  int64 `protobuf:"varint,3,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`
}

func (x *RevokeMessageReq) Reset() {
	*x = RevokeMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessageReq) ProtoMessage() {}

func (x *RevokeMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessageReq.ProtoReflect.Descriptor instead.
func (*RevokeMessageReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeMessageReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *RevokeMessageReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *RevokeMessageReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

type RevokeMessageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RevokeMsgId int64  `protobuf:"varint,1,opt,name=revoke_msg_id,json=revokeMsgId,proto3" json:"revoke_msg_id,omitempty"` // MSG_REVOKE 消息自身的 id
	Seq         int64  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Error       *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // code 30: 非本人消息 (时间窗/不存在走 500 明细)
}

func (x *RevokeMessageRsp) Reset() {
	*x = RevokeMessageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMessageRsp) ProtoMessage() {}

func (x *RevokeMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMessageRsp.ProtoReflect.Descriptor instead.
func (*RevokeMessageRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeMessageRsp) GetRevokeMsgId() int64 {
	if x != nil {
		return x.RevokeMsgId
	}
	return 0
}

func (x *RevokeMessageRsp) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RevokeMessageRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type MarkReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ConvId  int64 `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	ReadSeq int64 `protobuf:"varint,3,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"` // 客户端累积确认水位
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{10}
}

func (x *MarkReadReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MarkReadReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *MarkReadReq) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type MarkReadRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarkReadRsp) Reset() {
	*x = MarkReadRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkReadRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRsp) ProtoMessage() {}

func (x *MarkReadRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRsp.ProtoReflect.Descriptor instead.
func (*MarkReadRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{11}
}

type GetReadStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpUid  int64 `protobuf:"varint,1,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"` // 必须为会话成员 (code 25)
	ConvId int64 `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
}

func (x *GetReadStateReq) Reset() {
	*x = GetReadStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadStateReq) ProtoMessage() {}

func (x *GetReadStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadStateReq.ProtoReflect.Descriptor instead.
func (*GetReadStateReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{12}
}

func (x *GetReadStateReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *GetReadStateReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

type GetReadStateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States []*ReadState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"` // 每成员一行 (含查询者自己)
	Error  *Error       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetReadStateRsp) Reset() {
	*x = GetReadStateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadStateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadStateRsp) ProtoMessage() {}

func (x *GetReadStateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadStateRsp.ProtoReflect.Descriptor instead.
func (*GetReadStateRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{13}
}

func (x *GetReadStateRsp) GetStates() []*ReadState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *GetReadStateRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReadState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ReadSeq int64 `protobuf:"varint,2,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
}

func (x *ReadState) Reset() {
	*x = ReadState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadState) ProtoMessage() {}

func (x *ReadState) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadState.ProtoReflect.Descriptor instead.
func (*ReadState) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{14}
}

func (x *ReadState) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReadState) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type ListConversationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListConversationsReq) Reset() {
	*x = ListConversationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsReq) ProtoMessage() {}

func (x *ListConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsReq.ProtoReflect.Descriptor instead.
func (*ListConversationsReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{15}
}

func (x *ListConversationsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListConversationsReq) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type ConversationBrief struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conv        *Conv        `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	UnreadCount int64        `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	LastMessage *ConvMessage `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"` // 最近一条, ZSET recent 直接取
}

func (x *ConversationBrief) Reset() {
	*x = ConversationBrief{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConversationBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationBrief) ProtoMessage() {}

func (x *ConversationBrief) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationBrief.ProtoReflect.Descriptor instead.
func (*ConversationBrief) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{16}
}

func (x *ConversationBrief) GetConv() *Conv {
	if x != nil {
		return x.Conv
	}
	return nil
}

func (x *ConversationBrief) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationBrief) GetLastMessage() *ConvMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type ListConversationsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conversations []*ConversationBrief `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	HasMore       bool                 `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *ListConversationsRsp) Reset() {
	*x = ListConversationsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConversationsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRsp) ProtoMessage() {}

func (x *ListConversationsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRsp.ProtoReflect.Descriptor instead.
func (*ListConversationsRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{17}
}

func (x *ListConversationsRsp) GetConversations() []*ConversationBrief {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CreateConvReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       ConvType `protobuf:"varint,1,opt,name=type,proto3,enum=yim.ConvType" json:"type,omitempty"`
	MemberUids []int64  `protobuf:"varint,2,rep,packed,name=member_uids,json=memberUids,proto3" json:"member_uids,omitempty"`
	OwnerUid   int64    `protobuf:"varint,3,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"` // 发起者 (里程碑9): 群聊 = 群主 seed; 单聊用于好友校验归属
	Name       string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                          // 群名 (里程碑11, 建群时可带; 单聊忽略)
}

func (x *CreateConvReq) Reset() {
	*x = CreateConvReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConvReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConvReq) ProtoMessage() {}

func (x *CreateConvReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConvReq.ProtoReflect.Descriptor instead.
func (*CreateConvReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{18}
}

func (x *CreateConvReq) GetType() ConvType {
	if x != nil {
		return x.Type
	}
	return ConvType_CONV_UNKNOWN
}

func (x *CreateConvReq) GetMemberUids() []int64 {
	if x != nil {
		return x.MemberUids
	}
	return nil
}

func (x *CreateConvReq) GetOwnerUid() int64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *CreateConvReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateConvRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conv         *Conv  `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	AlreadyExist bool   `protobuf:"varint,2,opt,name=already_exist,json=alreadyExist,proto3" json:"already_exist,omitempty"` // 单聊重复创建: 返回已有会话
	Error        *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateConvRsp) Reset() {
	*x = CreateConvRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConvRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConvRsp) ProtoMessage() {}

func (x *CreateConvRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConvRsp.ProtoReflect.Descriptor instead.
func (*CreateConvRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{19}
}

func (x *CreateConvRsp) GetConv() *Conv {
	if x != nil {
		return x.Conv
	}
	return nil
}

func (x *CreateConvRsp) GetAlreadyExist() bool {
	if x != nil {
		return x.AlreadyExist
	}
	return false
}

func (x *CreateConvRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SearchMessagesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Keyword string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"` // 非空, 裁剪后 ≥1 rune
	Limit   int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`    // clamp 1..20, 缺省 20
}

func (x *SearchMessagesReq) Reset() {
	*x = SearchMessagesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesReq) ProtoMessage() {}

func (x *SearchMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesReq.ProtoReflect.Descriptor instead.
func (*SearchMessagesReq) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{20}
}

func (x *SearchMessagesReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SearchMessagesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchMessagesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages  []*ConvMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`    // 按时间倒序
	Truncated bool           `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"` // 超过 limit 截断 (前端可提示"仅显示最近部分")
}

func (x *SearchMessagesRsp) Reset() {
	*x = SearchMessagesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMessagesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesRsp) ProtoMessage() {}

func (x *SearchMessagesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesRsp.ProtoReflect.Descriptor instead.
func (*SearchMessagesRsp) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{21}
}

func (x *SearchMessagesRsp) GetMessages() []*ConvMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SearchMessagesRsp) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_service_message_proto protoreflect.FileDescriptor

var file_service_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x69, 0x6d, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f,
	0x6d, 0x55, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76,
	0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12,
	0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xca, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x6c, 0x6c,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x76, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x73,
	0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65,
	0x71, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x53, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x66, 0x6f,
	0x72, 0x65, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x65,
	0x66, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f,
	0x70, 0x55, 0x69, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x6c, 0x6c, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e,
	0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x74, 0x0a, 0x08, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x12, 0x32, 0x0a,
	0x0a, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x57, 0x61, 0x74, 0x65,
	0x72, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x0a, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b,
	0x73, 0x22, 0x8c, 0x01, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x73, 0x70, 0x32, 0x12, 0x22,
	0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x65, 0x71, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x2e, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x57, 0x61, 0x74,
	0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77,
	0x22, 0x50, 0x0a, 0x0a, 0x41, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x63, 0x6b,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x63, 0x6b, 0x53,
	0x65, 0x71, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x52, 0x73, 0x70,
	0x22, 0x59, 0x0a, 0x10, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x76, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x70, 0x55, 0x69, 0x64, 0x22, 0x6a, 0x0a, 0x10, 0x52,
	0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x0d, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x53, 0x0a, 0x0b, 0x4d, 0x61, 0x72, 0x6b, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x53, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b,
	0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x73, 0x70, 0x22, 0x41, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x15,
	0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6f, 0x70, 0x55, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x22, 0x5b,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x38, 0x0a, 0x09, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65,
	0x61, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65,
	0x61, 0x64, 0x53, 0x65, 0x71, 0x22, 0x4b, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x21, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x79, 0x69, 0x6d, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x72, 0x69, 0x65, 0x66, 0x12, 0x1d, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x76,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e,
	0x76, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x76, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x6f, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65,
	0x22, 0x84, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x52,
	0x65, 0x71, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f,
	0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x55, 0x69, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f,
	0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x76, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x76,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e,
	0x76, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x76, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x61, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x55,
	0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x5f, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79,
	0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x75, 0x6e,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x75,
	0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x2a, 0x48, 0x0a, 0x08, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x55, 0x4c, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x55, 0x4c, 0x4c, 0x5f, 0x53, 0x45, 0x51,
	0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x55, 0x4c, 0x4c,
	0x5f, 0x50, 0x41, 0x47, 0x45, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x57, 0x41, 0x52, 0x44, 0x10, 0x02,
	0x32, 0xc3, 0x04, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0b,
	0x50, 0x75, 0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x13, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x0d, 0x2e,
	0x79, 0x69, 0x6d, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x32, 0x1a, 0x0d, 0x2e, 0x79,
	0x69, 0x6d, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x73, 0x70, 0x32, 0x12, 0x2b, 0x0a, 0x07, 0x41,
	0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x12, 0x0f, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x41, 0x63, 0x6b,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x41, 0x63,
	0x6b, 0x50, 0x75, 0x73, 0x68, 0x52, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0d, 0x52, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x79, 0x69, 0x6d, 0x2e,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x15, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x52,
	0x65, 0x61, 0x64, 0x12, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4d, 0x61, 0x72, 0x6b,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e,
	0x79, 0x69, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x73, 0x70, 0x12, 0x40,
	0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x16, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x73, 0x70,
	0x12, 0x34, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x12, 0x12,
	0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x76, 0x52, 0x73, 0x70, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6d, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x79, 0x69, 0x6d, 0x3b, 0x79, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_message_proto_rawDescOnce sync.Once
	file_service_message_proto_rawDescData = file_service_message_proto_rawDesc
)

func file_service_message_proto_rawDescGZIP() []byte {
	file_service_message_proto_rawDescOnce.Do(func() {
		file_service_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_message_proto_rawDescData)
	})
	return file_service_message_proto_rawDescData
}

var file_service_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_message_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_service_message_proto_goTypes = []interface{}{
	(PullMode)(0),                // 0: yim.PullMode
	(*SendMessageReq)(nil),       // 1: yim.SendMessageReq
	(*SendMessageRsp)(nil),       // 2: yim.SendMessageRsp
	(*PullHistoryReq)(nil),       // 3: yim.PullHistoryReq
	(*PullHistoryRsp)(nil),       // 4: yim.PullHistoryRsp
	(*SyncReq2)(nil),             // 5: yim.SyncReq2
	(*SyncRsp2)(nil),             // 6: yim.SyncRsp2
	(*AckPushReq)(nil),           // 7: yim.AckPushReq
	(*AckPushRsp)(nil),           // 8: yim.AckPushRsp
	(*RevokeMessageReq)(nil),     // 9: yim.RevokeMessageReq
	(*RevokeMessageRsp)(nil),     // 10: yim.RevokeMessageRsp
	(*MarkReadReq)(nil),          // 11: yim.MarkReadReq
	(*MarkReadRsp)(nil),          // 12: yim.MarkReadRsp
	(*GetReadStateReq)(nil),      // 13: yim.GetReadStateReq
	(*GetReadStateRsp)(nil),      // 14: yim.GetReadStateRsp
	(*ReadState)(nil),            // 15: yim.ReadState
	(*ListConversationsReq)(nil), // 16: yim.ListConversationsReq
	(*ConversationBrief)(nil),    // 17: yim.ConversationBrief
	(*ListConversationsRsp)(nil), // 18: yim.ListConversationsRsp
	(*CreateConvReq)(nil),        // 19: yim.CreateConvReq
	(*CreateConvRsp)(nil),        // 20: yim.CreateConvRsp
	(*SearchMessagesReq)(nil),    // 21: yim.SearchMessagesReq
	(*SearchMessagesRsp)(nil),    // 22: yim.SearchMessagesRsp
	(*ConvMsgContent)(nil),       // 23: yim.ConvMsgContent
	(*Error)(nil),                // 24: yim.Error
	(*ConvMessage)(nil),          // 25: yim.ConvMessage
	(*ConvWatermark)(nil),        // 26: yim.ConvWatermark
	(*PageInfo)(nil),             // 27: yim.PageInfo
	(*Conv)(nil),                 // 28: yim.Conv
	(ConvType)(0),                // 29: yim.ConvType
}
var file_service_message_proto_depIdxs = []int32{
	23, // 0: yim.SendMessageReq.content:type_name -> yim.ConvMsgContent
	24, // 1: yim.SendMessageRsp.error:type_name -> yim.Error
	0,  // 2: yim.PullHistoryReq.mode:type_name -> yim.PullMode
	25, // 3: yim.PullHistoryRsp.messages:type_name -> yim.ConvMessage
	24, // 4: yim.PullHistoryRsp.error:type_name -> yim.Error
	26, // 5: yim.SyncReq2.watermarks:type_name -> yim.ConvWatermark
	25, // 6: yim.SyncRsp2.messages:type_name -> yim.ConvMessage
	26, // 7: yim.SyncRsp2.overflow:type_name -> yim.ConvWatermark
	24, // 8: yim.RevokeMessageRsp.error:type_name -> yim.Error
	15, // 9: yim.GetReadStateRsp.states:type_name -> yim.ReadState
	24, // 10: yim.GetReadStateRsp.error:type_name -> yim.Error
	27, // 11: yim.ListConversationsReq.page:type_name -> yim.PageInfo
	28, // 12: yim.ConversationBrief.conv:type_name -> yim.Conv
	25, // 13: yim.ConversationBrief.last_message:type_name -> yim.ConvMessage
	17, // 14: yim.ListConversationsRsp.conversations:type_name -> yim.ConversationBrief
	29, // 15: yim.CreateConvReq.type:type_name -> yim.ConvType
	28, // 16: yim.CreateConvRsp.conv:type_name -> yim.Conv
	24, // 17: yim.CreateConvRsp.error:type_name -> yim.Error
	25, // 18: yim.SearchMessagesRsp.messages:type_name -> yim.ConvMessage
	1,  // 19: yim.MessageService.SendMessage:input_type -> yim.SendMessageReq
	3,  // 20: yim.MessageService.PullHistory:input_type -> yim.PullHistoryReq
	5,  // 21: yim.MessageService.Sync:input_type -> yim.SyncReq2
	7,  // 22: yim.MessageService.AckPush:input_type -> yim.AckPushReq
	9,  // 23: yim.MessageService.RevokeMessage:input_type -> yim.RevokeMessageReq
	11, // 24: yim.MessageService.MarkRead:input_type -> yim.MarkReadReq
	13, // 25: yim.MessageService.GetReadState:input_type -> yim.GetReadStateReq
	16, // 26: yim.MessageService.ListConversations:input_type -> yim.ListConversationsReq
	21, // 27: yim.MessageService.SearchMessages:input_type -> yim.SearchMessagesReq
	19, // 28: yim.MessageService.CreateConv:input_type -> yim.CreateConvReq
	2,  // 29: yim.MessageService.SendMessage:output_type -> yim.SendMessageRsp
	4,  // 30: yim.MessageService.PullHistory:output_type -> yim.PullHistoryRsp
	6,  // 31: yim.MessageService.Sync:output_type -> yim.SyncRsp2
	8,  // 32: yim.MessageService.AckPush:output_type -> yim.AckPushRsp
	10, // 33: yim.MessageService.RevokeMessage:output_type -> yim.RevokeMessageRsp
	12, // 34: yim.MessageService.MarkRead:output_type -> yim.MarkReadRsp
	14, // 35: yim.MessageService.GetReadState:output_type -> yim.GetReadStateRsp
	18, // 36: yim.MessageService.ListConversations:output_type -> yim.ListConversationsRsp
	22, // 37: yim.MessageService.SearchMessages:output_type -> yim.SearchMessagesRsp
	20, // 38: yim.MessageService.CreateConv:output_type -> yim.CreateConvRsp
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_service_message_proto_init() }
func file_service_message_proto_init() {
	if File_service_message_proto != nil {
		return
	}
	file_common_proto_init()
	file_message_proto_init()
	file_protocol_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullHistoryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReq2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRsp2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckPushRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeMessageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkReadRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReadStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReadStateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConversationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConversationBrief); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConversationsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConvReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConvRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMessagesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMessagesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_message_proto_goTypes,
		DependencyIndexes: file_service_message_proto_depIdxs,
		EnumInfos:         file_service_message_proto_enumTypes,
		MessageInfos:      file_service_message_proto_msgTypes,
	}.Build()
	File_service_message_proto = out.File
	file_service_message_proto_rawDesc = nil
	file_service_message_proto_goTypes = nil
	file_service_message_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.16.3. DO NOT EDIT.

type MessageService interface {
	SendMessage(ctx context.Context, req *SendMessageReq) (res *SendMessageRsp, err error)
	PullHistory(ctx context.Context, req *PullHistoryReq) (res *PullHistoryRsp, err error)
	Sync(ctx context.Context, req *SyncReq2) (res *SyncRsp2, err error)
	AckPush(ctx context.Context, req *AckPushReq) (res *AckPushRsp, err error)
	RevokeMessage(ctx context.Context, req *RevokeMessageReq) (res *RevokeMessageRsp, err error)
	MarkRead(ctx context.Context, req *MarkReadReq) (res *MarkReadRsp, err error)
	GetReadState(ctx context.Context, req *GetReadStateReq) (res *GetReadStateRsp, err error)
	ListConversations(ctx context.Context, req *ListConversationsReq) (res *ListConversationsRsp, err error)
	SearchMessages(ctx context.Context, req *SearchMessagesReq) (res *SearchMessagesRsp, err error)
	CreateConv(ctx context.Context, req *CreateConvReq) (res *CreateConvRsp, err error)
}
