// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: service_job.proto

package yim

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 投递事件: 与 internal/message.PushEvent 同构 (发送事务提交后触发)
type DeliveryEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId      int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MaxSeq      int64 `protobuf:"varint,2,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"` // 本批增量水位 (当前单条消息, 预留批量)
	FromUid     int64 `protobuf:"varint,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	UserSyncSeq int64 `protobuf:"varint,4,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"` // 发送者用户级水位 (投递层按接收者单独 bump)
	MsgId       int64 `protobuf:"varint,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                     // 投递完成后回写 local_message.status=1 (防线3 扫表增量)
}

func (x *DeliveryEvent) Reset() {
	*x = DeliveryEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryEvent) ProtoMessage() {}

func (x *DeliveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryEvent.ProtoReflect.Descriptor instead.
func (*DeliveryEvent) Descriptor() ([]byte, []int) {
	return file_service_job_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryEvent) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *DeliveryEvent) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *DeliveryEvent) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *DeliveryEvent) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

func (x *DeliveryEvent) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

// 确认事件: 客户端累积确认 (取消 seq <= ack_seq 的重试定时)
type AckEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ConvId int64 `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	AckSeq int64 `protobuf:"varint,3,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
}

func (x *AckEvent) Reset() {
	*x = AckEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEvent) ProtoMessage() {}

func (x *AckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEvent.ProtoReflect.Descriptor instead.
func (*AckEvent) Descriptor() ([]byte, []int) {
	return file_service_job_proto_rawDescGZIP(), []int{1}
}

func (x *AckEvent) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AckEvent) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *AckEvent) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

var File_service_job_proto protoreflect.FileDescriptor

var file_service_job_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x69, 0x6d, 0x22, 0x97, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x76, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x53, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x22, 0x4e, 0x0a, 0x08, 0x41, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x63, 0x6b,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x63, 0x6b, 0x53,
	0x65, 0x71, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x79, 0x69, 0x6d, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x79,
	0x69, 0x6d, 0x3b, 0x79, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_job_proto_rawDescOnce sync.Once
	file_service_job_proto_rawDescData = file_service_job_proto_rawDesc
)

func file_service_job_proto_rawDescGZIP() []byte {
	file_service_job_proto_rawDescOnce.Do(func() {
		file_service_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_job_proto_rawDescData)
	})
	return file_service_job_proto_rawDescData
}

var file_service_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_job_proto_goTypes = []interface{}{
	(*DeliveryEvent)(nil), // 0: yim.DeliveryEvent
	(*AckEvent)(nil),      // 1: yim.AckEvent
}
var file_service_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_job_proto_init() }
func file_service_job_proto_init() {
	if File_service_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_job_proto_goTypes,
		DependencyIndexes: file_service_job_proto_depIdxs,
		MessageInfos:      file_service_job_proto_msgTypes,
	}.Build()
	File_service_job_proto = out.File
	file_service_job_proto_rawDesc = nil
	file_service_job_proto_goTypes = nil
	file_service_job_proto_depIdxs = nil
}

var _ context.Context
