// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: service_relation.proto

package yim

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Presence int32

const (
	Presence_PRESENCE_UNKNOWN Presence = 0
	Presence_PRESENCE_OFFLINE Presence = 1
	Presence_PRESENCE_ONLINE  Presence = 2
)

// Enum value maps for Presence.
var (
	Presence_name = map[int32]string{
		0: "PRESENCE_UNKNOWN",
		1: "PRESENCE_OFFLINE",
		2: "PRESENCE_ONLINE",
	}
	Presence_value = map[string]int32{
		"PRESENCE_UNKNOWN": 0,
		"PRESENCE_OFFLINE": 1,
		"PRESENCE_ONLINE":  2,
	}
)

func (x Presence) Enum() *Presence {
	p := new(Presence)
	*p = x
	return p
}

func (x Presence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Presence) Descriptor() protoreflect.EnumDescriptor {
	return file_service_relation_proto_enumTypes[0].Descriptor()
}

func (Presence) Type() protoreflect.EnumType {
	return &file_service_relation_proto_enumTypes[0]
}

func (x Presence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Presence.Descriptor instead.
func (Presence) EnumDescriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{0}
}

type SendFriendRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUid int64  `protobuf:"varint,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"` // 网关注入 (token 身份)
	ToUid   int64  `protobuf:"varint,2,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 验证消息, 可空
}

func (x *SendFriendRequestReq) Reset() {
	*x = SendFriendRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestReq) ProtoMessage() {}

func (x *SendFriendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestReq.ProtoReflect.Descriptor instead.
func (*SendFriendRequestReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{0}
}

func (x *SendFriendRequestReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *SendFriendRequestReq) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *SendFriendRequestReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendFriendRequestRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 20 已是好友; 成功时 error 为空
}

func (x *SendFriendRequestRsp) Reset() {
	*x = SendFriendRequestRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendRequestRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRsp) ProtoMessage() {}

func (x *SendFriendRequestRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRsp.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HandleFriendRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpUid   int64 `protobuf:"varint,1,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`       // 操作者, 必须等于 to_uid
	FromUid int64 `protobuf:"varint,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"` // 申请发起者
	Accept  bool  `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
}

func (x *HandleFriendRequestReq) Reset() {
	*x = HandleFriendRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleFriendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestReq) ProtoMessage() {}

func (x *HandleFriendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestReq.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{2}
}

func (x *HandleFriendRequestReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *HandleFriendRequestReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *HandleFriendRequestReq) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type HandleFriendRequestRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 21 不存在/无权; 26 已处理
}

func (x *HandleFriendRequestRsp) Reset() {
	*x = HandleFriendRequestRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleFriendRequestRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestRsp) ProtoMessage() {}

func (x *HandleFriendRequestRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestRsp.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{3}
}

func (x *HandleFriendRequestRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FriendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUid      int64  `protobuf:"varint,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	ToUid        int64  `protobuf:"varint,2,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Message      string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status       int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 0 pending 1 accepted 2 rejected
	CreateTimeMs int64  `protobuf:"varint,5,opt,name=create_time_ms,json=createTimeMs,proto3" json:"create_time_ms,omitempty"`
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{4}
}

func (x *FriendRequest) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *FriendRequest) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *FriendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequest) GetCreateTimeMs() int64 {
	if x != nil {
		return x.CreateTimeMs
	}
	return 0
}

type ListFriendRequestsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Incoming bool  `protobuf:"varint,2,opt,name=incoming,proto3" json:"incoming,omitempty"` // true=收到的申请, false=我发出的
}

func (x *ListFriendRequestsReq) Reset() {
	*x = ListFriendRequestsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFriendRequestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsReq) ProtoMessage() {}

func (x *ListFriendRequestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsReq.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{5}
}

func (x *ListFriendRequestsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListFriendRequestsReq) GetIncoming() bool {
	if x != nil {
		return x.Incoming
	}
	return false
}

type ListFriendRequestsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*FriendRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Error    *Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListFriendRequestsRsp) Reset() {
	*x = ListFriendRequestsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFriendRequestsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsRsp) ProtoMessage() {}

func (x *ListFriendRequestsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsRsp.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{6}
}

func (x *ListFriendRequestsRsp) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListFriendRequestsRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FriendBrief struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname     string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar       string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreateTimeMs int64  `protobuf:"varint,4,opt,name=create_time_ms,json=createTimeMs,proto3" json:"create_time_ms,omitempty"` // 成为好友的时间
}

func (x *FriendBrief) Reset() {
	*x = FriendBrief{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendBrief) ProtoMessage() {}

func (x *FriendBrief) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendBrief.ProtoReflect.Descriptor instead.
func (*FriendBrief) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{7}
}

func (x *FriendBrief) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FriendBrief) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FriendBrief) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FriendBrief) GetCreateTimeMs() int64 {
	if x != nil {
		return x.CreateTimeMs
	}
	return 0
}

type ListFriendsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListFriendsReq) Reset() {
	*x = ListFriendsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsReq) ProtoMessage() {}

func (x *ListFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsReq.ProtoReflect.Descriptor instead.
func (*ListFriendsReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{8}
}

func (x *ListFriendsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListFriendsReq) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListFriendsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*FriendBrief `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	HasMore bool           `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Error   *Error         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListFriendsRsp) Reset() {
	*x = ListFriendsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFriendsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRsp) ProtoMessage() {}

func (x *ListFriendsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRsp.ProtoReflect.Descriptor instead.
func (*ListFriendsRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{9}
}

func (x *ListFriendsRsp) GetFriends() []*FriendBrief {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *ListFriendsRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListFriendsRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpUid     int64 `protobuf:"varint,1,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"`
	FriendUid int64 `protobuf:"varint,2,opt,name=friend_uid,json=friendUid,proto3" json:"friend_uid,omitempty"`
}

func (x *DeleteFriendReq) Reset() {
	*x = DeleteFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendReq) ProtoMessage() {}

func (x *DeleteFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendReq.ProtoReflect.Descriptor instead.
func (*DeleteFriendReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFriendReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *DeleteFriendReq) GetFriendUid() int64 {
	if x != nil {
		return x.FriendUid
	}
	return 0
}

type DeleteFriendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteFriendRsp) Reset() {
	*x = DeleteFriendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFriendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRsp) ProtoMessage() {}

func (x *DeleteFriendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRsp.ProtoReflect.Descriptor instead.
func (*DeleteFriendRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFriendRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CheckFriendshipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AUid int64 `protobuf:"varint,1,opt,name=a_uid,json=aUid,proto3" json:"a_uid,omitempty"`
	BUid int64 `protobuf:"varint,2,opt,name=b_uid,json=bUid,proto3" json:"b_uid,omitempty"`
}

func (x *CheckFriendshipReq) Reset() {
	*x = CheckFriendshipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFriendshipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipReq) ProtoMessage() {}

func (x *CheckFriendshipReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipReq.ProtoReflect.Descriptor instead.
func (*CheckFriendshipReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{12}
}

func (x *CheckFriendshipReq) GetAUid() int64 {
	if x != nil {
		return x.AUid
	}
	return 0
}

func (x *CheckFriendshipReq) GetBUid() int64 {
	if x != nil {
		return x.BUid
	}
	return 0
}

type CheckFriendshipRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFriend bool `protobuf:"varint,1,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
}

func (x *CheckFriendshipRsp) Reset() {
	*x = CheckFriendshipRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFriendshipRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipRsp) ProtoMessage() {}

func (x *CheckFriendshipRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipRsp.ProtoReflect.Descriptor instead.
func (*CheckFriendshipRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{13}
}

func (x *CheckFriendshipRsp) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

type AddGroupMembersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId     int64   `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MemberUids []int64 `protobuf:"varint,2,rep,packed,name=member_uids,json=memberUids,proto3" json:"member_uids,omitempty"`
	OwnerUid   int64   `protobuf:"varint,3,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"` // 操作者: 建群 = 群主 (首行 role=1); 拉人 = 必须已是群主
}

func (x *AddGroupMembersReq) Reset() {
	*x = AddGroupMembersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupMembersReq) ProtoMessage() {}

func (x *AddGroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupMembersReq.ProtoReflect.Descriptor instead.
func (*AddGroupMembersReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{14}
}

func (x *AddGroupMembersReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *AddGroupMembersReq) GetMemberUids() []int64 {
	if x != nil {
		return x.MemberUids
	}
	return nil
}

func (x *AddGroupMembersReq) GetOwnerUid() int64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

type AddGroupMembersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddGroupMembersRsp) Reset() {
	*x = AddGroupMembersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupMembersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupMembersRsp) ProtoMessage() {}

func (x *AddGroupMembersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupMembersRsp.ProtoReflect.Descriptor instead.
func (*AddGroupMembersRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{15}
}

func (x *AddGroupMembersRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemoveGroupMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpUid     int64 `protobuf:"varint,1,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"` // 必须是群主
	ConvId    int64 `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	TargetUid int64 `protobuf:"varint,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
}

func (x *RemoveGroupMemberReq) Reset() {
	*x = RemoveGroupMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGroupMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberReq) ProtoMessage() {}

func (x *RemoveGroupMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberReq.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveGroupMemberReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *RemoveGroupMemberReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *RemoveGroupMemberReq) GetTargetUid() int64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

type RemoveGroupMemberRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RemoveGroupMemberRsp) Reset() {
	*x = RemoveGroupMemberRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGroupMemberRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberRsp) ProtoMessage() {}

func (x *RemoveGroupMemberRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberRsp.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveGroupMemberRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type QuitGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ConvId int64 `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
}

func (x *QuitGroupReq) Reset() {
	*x = QuitGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupReq) ProtoMessage() {}

func (x *QuitGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupReq.ProtoReflect.Descriptor instead.
func (*QuitGroupReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{18}
}

func (x *QuitGroupReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *QuitGroupReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

type QuitGroupRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *QuitGroupRsp) Reset() {
	*x = QuitGroupRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitGroupRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupRsp) ProtoMessage() {}

func (x *QuitGroupRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupRsp.ProtoReflect.Descriptor instead.
func (*QuitGroupRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{19}
}

func (x *QuitGroupRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GroupMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role       int32  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"` // 0 member 1 owner
	Nickname   string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar     string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	JoinTimeMs int64  `protobuf:"varint,5,opt,name=join_time_ms,json=joinTimeMs,proto3" json:"join_time_ms,omitempty"`
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{20}
}

func (x *GroupMember) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GroupMember) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupMember) GetJoinTimeMs() int64 {
	if x != nil {
		return x.JoinTimeMs
	}
	return 0
}

type ListGroupMembersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
}

func (x *ListGroupMembersReq) Reset() {
	*x = ListGroupMembersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersReq) ProtoMessage() {}

func (x *ListGroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersReq.ProtoReflect.Descriptor instead.
func (*ListGroupMembersReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{21}
}

func (x *ListGroupMembersReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

type ListGroupMembersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*GroupMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Error   *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListGroupMembersRsp) Reset() {
	*x = ListGroupMembersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupMembersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRsp) ProtoMessage() {}

func (x *ListGroupMembersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersRsp.ProtoReflect.Descriptor instead.
func (*ListGroupMembersRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{22}
}

func (x *ListGroupMembersRsp) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListGroupMembersRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 改群信息 (里程碑11): 仅群主 (code 23); 字段按传入与否覆盖 (空串=不改名, 用
// update_mask 语义简化为"字段级可选", protojson 缺省字段不覆盖)
type UpdateGroupInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpUid  int64  `protobuf:"varint,1,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"` // 操作者, 必须是群主
	ConvId int64  `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`     // 传才更新 (空串视为不改)
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"` // 群头像相对 URL, 传才更新
}

func (x *UpdateGroupInfoReq) Reset() {
	*x = UpdateGroupInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoReq) ProtoMessage() {}

func (x *UpdateGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateGroupInfoReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateGroupInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 23 非群主 / 25 非成员
}

func (x *UpdateGroupInfoRsp) Reset() {
	*x = UpdateGroupInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoRsp) ProtoMessage() {}

func (x *UpdateGroupInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoRsp.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateGroupInfoRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetProfilesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []int64 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"` // clamp 50
}

func (x *GetProfilesReq) Reset() {
	*x = GetProfilesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesReq) ProtoMessage() {}

func (x *GetProfilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesReq.ProtoReflect.Descriptor instead.
func (*GetProfilesReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{25}
}

func (x *GetProfilesReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type GetProfilesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*UserProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Error    *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetProfilesRsp) Reset() {
	*x = GetProfilesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfilesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesRsp) ProtoMessage() {}

func (x *GetProfilesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesRsp.ProtoReflect.Descriptor instead.
func (*GetProfilesRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{26}
}

func (x *GetProfilesRsp) GetProfiles() []*UserProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *GetProfilesRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SearchUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`           // 纯数字 = uid 精确匹配 OR 昵称前缀; 否则昵称前缀
	OpUid   int64  `protobuf:"varint,2,opt,name=op_uid,json=opUid,proto3" json:"op_uid,omitempty"` // 排除自己
	Limit   int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`              // clamp 20
}

func (x *SearchUsersReq) Reset() {
	*x = SearchUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersReq) ProtoMessage() {}

func (x *SearchUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersReq.ProtoReflect.Descriptor instead.
func (*SearchUsersReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{27}
}

func (x *SearchUsersReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUsersReq) GetOpUid() int64 {
	if x != nil {
		return x.OpUid
	}
	return 0
}

func (x *SearchUsersReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUsersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*UserProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Error    *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SearchUsersRsp) Reset() {
	*x = SearchUsersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUsersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRsp) ProtoMessage() {}

func (x *SearchUsersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRsp.ProtoReflect.Descriptor instead.
func (*SearchUsersRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{28}
}

func (x *SearchUsersRsp) GetProfiles() []*UserProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *SearchUsersRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"` // 相对 URL (/files/avatar/..), 客户端拼 base
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{29}
}

func (x *UserProfile) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateProfileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // 空 = 不改
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 空 = 不改
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateProfileReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateProfileReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateProfileRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *UserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Error   *Error       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 27 昵称被占用
}

func (x *UpdateProfileRsp) Reset() {
	*x = UpdateProfileRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRsp) ProtoMessage() {}

func (x *UpdateProfileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRsp.ProtoReflect.Descriptor instead.
func (*UpdateProfileRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateProfileRsp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UpdateProfileRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPresenceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []int64 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"` // clamp 50
}

func (x *GetPresenceReq) Reset() {
	*x = GetPresenceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPresenceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceReq) ProtoMessage() {}

func (x *GetPresenceReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceReq.ProtoReflect.Descriptor instead.
func (*GetPresenceReq) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{32}
}

func (x *GetPresenceReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type PresenceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Presence Presence `protobuf:"varint,2,opt,name=presence,proto3,enum=yim.Presence" json:"presence,omitempty"`
}

func (x *PresenceInfo) Reset() {
	*x = PresenceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceInfo) ProtoMessage() {}

func (x *PresenceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceInfo.ProtoReflect.Descriptor instead.
func (*PresenceInfo) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{33}
}

func (x *PresenceInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PresenceInfo) GetPresence() Presence {
	if x != nil {
		return x.Presence
	}
	return Presence_PRESENCE_UNKNOWN
}

type GetPresenceRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Presences []*PresenceInfo `protobuf:"bytes,1,rep,name=presences,proto3" json:"presences,omitempty"`
	Error     *Error          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetPresenceRsp) Reset() {
	*x = GetPresenceRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_relation_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPresenceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRsp) ProtoMessage() {}

func (x *GetPresenceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_relation_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRsp.ProtoReflect.Descriptor instead.
func (*GetPresenceRsp) Descriptor() ([]byte, []int) {
	return file_service_relation_proto_rawDescGZIP(), []int{34}
}

func (x *GetPresenceRsp) GetPresences() []*PresenceInfo {
	if x != nil {
		return x.Presences
	}
	return nil
}

func (x *GetPresenceRsp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_service_relation_proto protoreflect.FileDescriptor

var file_service_relation_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x69, 0x6d, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x14, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x38, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x62, 0x0a, 0x16, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x70, 0x55, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72,
	0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x22, 0x3a, 0x0a,
	0x16, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66,
	0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x24, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x4d, 0x73, 0x22, 0x45, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0x69, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x79, 0x0a, 0x0b, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x42, 0x72, 0x69, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x24, 0x0a, 0x0e,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x4d, 0x73, 0x22, 0x45, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x79, 0x0a, 0x0e, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x07, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79,
	0x69, 0x6d, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52, 0x07,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f,
	0x72, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x70, 0x55, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x55, 0x69, 0x64, 0x22, 0x33, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70,
	0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05, 0x61, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x61, 0x55, 0x69, 0x64, 0x12, 0x13, 0x0a,
	0x05, 0x62, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x62, 0x55,
	0x69, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x68, 0x69, 0x70, 0x52, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x22, 0x6b, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x76, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x75,
	0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x55, 0x69, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55,
	0x69, 0x64, 0x22, 0x36, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x65, 0x0a, 0x14, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6f, 0x70, 0x55, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x76, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x69,
	0x64, 0x22, 0x38, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x39, 0x0a, 0x0c, 0x51,
	0x75, 0x69, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x89, 0x01, 0x0a, 0x0b, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x20, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x4d, 0x73, 0x22, 0x2e, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x76, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79,
	0x69, 0x6d, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x70, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6f, 0x70, 0x55, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x36, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73,
	0x70, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x60, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x79, 0x69, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x57, 0x0a, 0x0e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x70, 0x55, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x60, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x53, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x58, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x60, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x69, 0x6d,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x4b, 0x0a,
	0x0c, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x29, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x63, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x09,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x09, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x20, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79,
	0x69, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a,
	0x4b, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x50,
	0x52, 0x45, 0x53, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x52, 0x45, 0x53, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x4f, 0x46,
	0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x45, 0x53, 0x45,
	0x4e, 0x43, 0x45, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x32, 0xef, 0x07, 0x0a,
	0x0f, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x49, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x13, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x4c, 0x0a, 0x12,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x12, 0x1a, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x52, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x79, 0x69, 0x6d, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12,
	0x43, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68,
	0x69, 0x70, 0x12, 0x17, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x68, 0x69,
	0x70, 0x52, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x17, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x41, 0x64,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x11, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19,
	0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x79, 0x69, 0x6d, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x11, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12,
	0x43, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x17, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a,
	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x13, 0x2e, 0x79,
	0x69, 0x6d, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15,
	0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x73, 0x70, 0x42, 0x22,
	0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6d,
	0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x79, 0x69, 0x6d, 0x3b, 0x79,
	0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_relation_proto_rawDescOnce sync.Once
	file_service_relation_proto_rawDescData = file_service_relation_proto_rawDesc
)

func file_service_relation_proto_rawDescGZIP() []byte {
	file_service_relation_proto_rawDescOnce.Do(func() {
		file_service_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_relation_proto_rawDescData)
	})
	return file_service_relation_proto_rawDescData
}

var file_service_relation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_service_relation_proto_goTypes = []interface{}{
	(Presence)(0),                  // 0: yim.Presence
	(*SendFriendRequestReq)(nil),   // 1: yim.SendFriendRequestReq
	(*SendFriendRequestRsp)(nil),   // 2: yim.SendFriendRequestRsp
	(*HandleFriendRequestReq)(nil), // 3: yim.HandleFriendRequestReq
	(*HandleFriendRequestRsp)(nil), // 4: yim.HandleFriendRequestRsp
	(*FriendRequest)(nil),          // 5: yim.FriendRequest
	(*ListFriendRequestsReq)(nil),  // 6: yim.ListFriendRequestsReq
	(*ListFriendRequestsRsp)(nil),  // 7: yim.ListFriendRequestsRsp
	(*FriendBrief)(nil),            // 8: yim.FriendBrief
	(*ListFriendsReq)(nil),         // 9: yim.ListFriendsReq
	(*ListFriendsRsp)(nil),         // 10: yim.ListFriendsRsp
	(*DeleteFriendReq)(nil),        // 11: yim.DeleteFriendReq
	(*DeleteFriendRsp)(nil),        // 12: yim.DeleteFriendRsp
	(*CheckFriendshipReq)(nil),     // 13: yim.CheckFriendshipReq
	(*CheckFriendshipRsp)(nil),     // 14: yim.CheckFriendshipRsp
	(*AddGroupMembersReq)(nil),     // 15: yim.AddGroupMembersReq
	(*AddGroupMembersRsp)(nil),     // 16: yim.AddGroupMembersRsp
	(*RemoveGroupMemberReq)(nil),   // 17: yim.RemoveGroupMemberReq
	(*RemoveGroupMemberRsp)(nil),   // 18: yim.RemoveGroupMemberRsp
	(*QuitGroupReq)(nil),           // 19: yim.QuitGroupReq
	(*QuitGroupRsp)(nil),           // 20: yim.QuitGroupRsp
	(*GroupMember)(nil),            // 21: yim.GroupMember
	(*ListGroupMembersReq)(nil),    // 22: yim.ListGroupMembersReq
	(*ListGroupMembersRsp)(nil),    // 23: yim.ListGroupMembersRsp
	(*UpdateGroupInfoReq)(nil),     // 24: yim.UpdateGroupInfoReq
	(*UpdateGroupInfoRsp)(nil),     // 25: yim.UpdateGroupInfoRsp
	(*GetProfilesReq)(nil),         // 26: yim.GetProfilesReq
	(*GetProfilesRsp)(nil),         // 27: yim.GetProfilesRsp
	(*SearchUsersReq)(nil),         // 28: yim.SearchUsersReq
	(*SearchUsersRsp)(nil),         // 29: yim.SearchUsersRsp
	(*UserProfile)(nil),            // 30: yim.UserProfile
	(*UpdateProfileReq)(nil),       // 31: yim.UpdateProfileReq
	(*UpdateProfileRsp)(nil),       // 32: yim.UpdateProfileRsp
	(*GetPresenceReq)(nil),         // 33: yim.GetPresenceReq
	(*PresenceInfo)(nil),           // 34: yim.PresenceInfo
	(*GetPresenceRsp)(nil),         // 35: yim.GetPresenceRsp
	(*Error)(nil),                  // 36: yim.Error
	(*PageInfo)(nil),               // 37: yim.PageInfo
}
var file_service_relation_proto_depIdxs = []int32{
	36, // 0: yim.SendFriendRequestRsp.error:type_name -> yim.Error
	36, // 1: yim.HandleFriendRequestRsp.error:type_name -> yim.Error
	5,  // 2: yim.ListFriendRequestsRsp.requests:type_name -> yim.FriendRequest
	36, // 3: yim.ListFriendRequestsRsp.error:type_name -> yim.Error
	37, // 4: yim.ListFriendsReq.page:type_name -> yim.PageInfo
	8,  // 5: yim.ListFriendsRsp.friends:type_name -> yim.FriendBrief
	36, // 6: yim.ListFriendsRsp.error:type_name -> yim.Error
	36, // 7: yim.DeleteFriendRsp.error:type_name -> yim.Error
	36, // 8: yim.AddGroupMembersRsp.error:type_name -> yim.Error
	36, // 9: yim.RemoveGroupMemberRsp.error:type_name -> yim.Error
	36, // 10: yim.QuitGroupRsp.error:type_name -> yim.Error
	21, // 11: yim.ListGroupMembersRsp.members:type_name -> yim.GroupMember
	36, // 12: yim.ListGroupMembersRsp.error:type_name -> yim.Error
	36, // 13: yim.UpdateGroupInfoRsp.error:type_name -> yim.Error
	30, // 14: yim.GetProfilesRsp.profiles:type_name -> yim.UserProfile
	36, // 15: yim.GetProfilesRsp.error:type_name -> yim.Error
	30, // 16: yim.SearchUsersRsp.profiles:type_name -> yim.UserProfile
	36, // 17: yim.SearchUsersRsp.error:type_name -> yim.Error
	30, // 18: yim.UpdateProfileRsp.profile:type_name -> yim.UserProfile
	36, // 19: yim.UpdateProfileRsp.error:type_name -> yim.Error
	0,  // 20: yim.PresenceInfo.presence:type_name -> yim.Presence
	34, // 21: yim.GetPresenceRsp.presences:type_name -> yim.PresenceInfo
	36, // 22: yim.GetPresenceRsp.error:type_name -> yim.Error
	1,  // 23: yim.RelationService.SendFriendRequest:input_type -> yim.SendFriendRequestReq
	3,  // 24: yim.RelationService.HandleFriendRequest:input_type -> yim.HandleFriendRequestReq
	6,  // 25: yim.RelationService.ListFriendRequests:input_type -> yim.ListFriendRequestsReq
	9,  // 26: yim.RelationService.ListFriends:input_type -> yim.ListFriendsReq
	11, // 27: yim.RelationService.DeleteFriend:input_type -> yim.DeleteFriendReq
	13, // 28: yim.RelationService.CheckFriendship:input_type -> yim.CheckFriendshipReq
	15, // 29: yim.RelationService.AddGroupMembers:input_type -> yim.AddGroupMembersReq
	17, // 30: yim.RelationService.RemoveGroupMember:input_type -> yim.RemoveGroupMemberReq
	19, // 31: yim.RelationService.QuitGroup:input_type -> yim.QuitGroupReq
	22, // 32: yim.RelationService.ListGroupMembers:input_type -> yim.ListGroupMembersReq
	24, // 33: yim.RelationService.UpdateGroupInfo:input_type -> yim.UpdateGroupInfoReq
	26, // 34: yim.RelationService.GetProfiles:input_type -> yim.GetProfilesReq
	28, // 35: yim.RelationService.SearchUsers:input_type -> yim.SearchUsersReq
	31, // 36: yim.RelationService.UpdateProfile:input_type -> yim.UpdateProfileReq
	33, // 37: yim.RelationService.GetPresence:input_type -> yim.GetPresenceReq
	2,  // 38: yim.RelationService.SendFriendRequest:output_type -> yim.SendFriendRequestRsp
	4,  // 39: yim.RelationService.HandleFriendRequest:output_type -> yim.HandleFriendRequestRsp
	7,  // 40: yim.RelationService.ListFriendRequests:output_type -> yim.ListFriendRequestsRsp
	10, // 41: yim.RelationService.ListFriends:output_type -> yim.ListFriendsRsp
	12, // 42: yim.RelationService.DeleteFriend:output_type -> yim.DeleteFriendRsp
	14, // 43: yim.RelationService.CheckFriendship:output_type -> yim.CheckFriendshipRsp
	16, // 44: yim.RelationService.AddGroupMembers:output_type -> yim.AddGroupMembersRsp
	18, // 45: yim.RelationService.RemoveGroupMember:output_type -> yim.RemoveGroupMemberRsp
	20, // 46: yim.RelationService.QuitGroup:output_type -> yim.QuitGroupRsp
	23, // 47: yim.RelationService.ListGroupMembers:output_type -> yim.ListGroupMembersRsp
	25, // 48: yim.RelationService.UpdateGroupInfo:output_type -> yim.UpdateGroupInfoRsp
	27, // 49: yim.RelationService.GetProfiles:output_type -> yim.GetProfilesRsp
	29, // 50: yim.RelationService.SearchUsers:output_type -> yim.SearchUsersRsp
	32, // 51: yim.RelationService.UpdateProfile:output_type -> yim.UpdateProfileRsp
	35, // 52: yim.RelationService.GetPresence:output_type -> yim.GetPresenceRsp
	38, // [38:53] is the sub-list for method output_type
	23, // [23:38] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_service_relation_proto_init() }
func file_service_relation_proto_init() {
	if File_service_relation_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_relation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFriendRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFriendRequestRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleFriendRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleFriendRequestRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFriendRequestsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFriendRequestsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendBrief); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFriendsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFriendsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFriendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFriendshipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFriendshipRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupMembersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupMembersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGroupMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGroupMemberRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitGroupRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupMembersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupMembersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfilesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfilesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchUsersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPresenceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_relation_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPresenceRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_relation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_relation_proto_goTypes,
		DependencyIndexes: file_service_relation_proto_depIdxs,
		EnumInfos:         file_service_relation_proto_enumTypes,
		MessageInfos:      file_service_relation_proto_msgTypes,
	}.Build()
	File_service_relation_proto = out.File
	file_service_relation_proto_rawDesc = nil
	file_service_relation_proto_goTypes = nil
	file_service_relation_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.16.3. DO NOT EDIT.

type RelationService interface {
	SendFriendRequest(ctx context.Context, req *SendFriendRequestReq) (res *SendFriendRequestRsp, err error)
	HandleFriendRequest(ctx context.Context, req *HandleFriendRequestReq) (res *HandleFriendRequestRsp, err error)
	ListFriendRequests(ctx context.Context, req *ListFriendRequestsReq) (res *ListFriendRequestsRsp, err error)
	ListFriends(ctx context.Context, req *ListFriendsReq) (res *ListFriendsRsp, err error)
	DeleteFriend(ctx context.Context, req *DeleteFriendReq) (res *DeleteFriendRsp, err error)
	CheckFriendship(ctx context.Context, req *CheckFriendshipReq) (res *CheckFriendshipRsp, err error)
	AddGroupMembers(ctx context.Context, req *AddGroupMembersReq) (res *AddGroupMembersRsp, err error)
	RemoveGroupMember(ctx context.Context, req *RemoveGroupMemberReq) (res *RemoveGroupMemberRsp, err error)
	QuitGroup(ctx context.Context, req *QuitGroupReq) (res *QuitGroupRsp, err error)
	ListGroupMembers(ctx context.Context, req *ListGroupMembersReq) (res *ListGroupMembersRsp, err error)
	UpdateGroupInfo(ctx context.Context, req *UpdateGroupInfoReq) (res *UpdateGroupInfoRsp, err error)
	GetProfiles(ctx context.Context, req *GetProfilesReq) (res *GetProfilesRsp, err error)
	SearchUsers(ctx context.Context, req *SearchUsersReq) (res *SearchUsersRsp, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileReq) (res *UpdateProfileRsp, err error)
	GetPresence(ctx context.Context, req *GetPresenceReq) (res *GetPresenceRsp, err error)
}
