// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: service_comet.proto

package yim

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId    string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 多端: 精确到设备; 空串 = 推该 uid 全部在线设备
	ConvId      int64  `protobuf:"varint,3,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MaxSeq      int64  `protobuf:"varint,4,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	FromUid     int64  `protobuf:"varint,5,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	UserSyncSeq int64  `protobuf:"varint,6,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"`
}

func (x *PushMessageReq) Reset() {
	*x = PushMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageReq) ProtoMessage() {}

func (x *PushMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageReq.ProtoReflect.Descriptor instead.
func (*PushMessageReq) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessageReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PushMessageReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PushMessageReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *PushMessageReq) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *PushMessageReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *PushMessageReq) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

type PushMessageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delivered bool `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"` // false: 设备不在线, Job 走离线箱
}

func (x *PushMessageRsp) Reset() {
	*x = PushMessageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageRsp) ProtoMessage() {}

func (x *PushMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageRsp.ProtoReflect.Descriptor instead.
func (*PushMessageRsp) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessageRsp) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

type KickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId    string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 被踢设备; 空 = 踢全部
	Reason      string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	UserSyncSeq int64  `protobuf:"varint,4,opt,name=user_sync_seq,json=userSyncSeq,proto3" json:"user_sync_seq,omitempty"`
}

func (x *KickReq) Reset() {
	*x = KickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickReq) ProtoMessage() {}

func (x *KickReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickReq.ProtoReflect.Descriptor instead.
func (*KickReq) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{2}
}

func (x *KickReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *KickReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KickReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickReq) GetUserSyncSeq() int64 {
	if x != nil {
		return x.UserSyncSeq
	}
	return 0
}

type KickRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KickRsp) Reset() {
	*x = KickRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRsp) ProtoMessage() {}

func (x *KickRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRsp.ProtoReflect.Descriptor instead.
func (*KickRsp) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{3}
}

type DrainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeoutMs int32 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // 排水窗口, 超时强制断开
}

func (x *DrainReq) Reset() {
	*x = DrainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainReq) ProtoMessage() {}

func (x *DrainReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainReq.ProtoReflect.Descriptor instead.
func (*DrainReq) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{4}
}

func (x *DrainReq) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DrainRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainingConnections int32 `protobuf:"varint,2,opt,name=remaining_connections,json=remainingConnections,proto3" json:"remaining_connections,omitempty"`
}

func (x *DrainRsp) Reset() {
	*x = DrainRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrainRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRsp) ProtoMessage() {}

func (x *DrainRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRsp.ProtoReflect.Descriptor instead.
func (*DrainRsp) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{5}
}

func (x *DrainRsp) GetRemainingConnections() int32 {
	if x != nil {
		return x.RemainingConnections
	}
	return 0
}

type CometStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CometStatsReq) Reset() {
	*x = CometStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometStatsReq) ProtoMessage() {}

func (x *CometStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometStatsReq.ProtoReflect.Descriptor instead.
func (*CometStatsReq) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{6}
}

type CometStatsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnlineConnections     int64   `protobuf:"varint,1,opt,name=online_connections,json=onlineConnections,proto3" json:"online_connections,omitempty"`
	RoomsCount            int64   `protobuf:"varint,2,opt,name=rooms_count,json=roomsCount,proto3" json:"rooms_count,omitempty"`
	CpuUsage              float64 `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	HeartbeatTimeoutCount int64   `protobuf:"varint,4,opt,name=heartbeat_timeout_count,json=heartbeatTimeoutCount,proto3" json:"heartbeat_timeout_count,omitempty"`
}

func (x *CometStatsRsp) Reset() {
	*x = CometStatsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_comet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometStatsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometStatsRsp) ProtoMessage() {}

func (x *CometStatsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_comet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometStatsRsp.ProtoReflect.Descriptor instead.
func (*CometStatsRsp) Descriptor() ([]byte, []int) {
	return file_service_comet_proto_rawDescGZIP(), []int{7}
}

func (x *CometStatsRsp) GetOnlineConnections() int64 {
	if x != nil {
		return x.OnlineConnections
	}
	return 0
}

func (x *CometStatsRsp) GetRoomsCount() int64 {
	if x != nil {
		return x.RoomsCount
	}
	return 0
}

func (x *CometStatsRsp) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *CometStatsRsp) GetHeartbeatTimeoutCount() int64 {
	if x != nil {
		return x.HeartbeatTimeoutCount
	}
	return 0
}

var File_service_comet_proto protoreflect.FileDescriptor

var file_service_comet_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x69, 0x6d, 0x22, 0xb0, 0x01, 0x0a, 0x0e, 0x50,
	0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x65, 0x71,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x53, 0x65, 0x71, 0x12, 0x19,
	0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x22, 0x2e, 0x0a,
	0x0e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x22, 0x74, 0x0a,
	0x07, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x22, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63,
	0x53, 0x65, 0x71, 0x22, 0x09, 0x0a, 0x07, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x73, 0x70, 0x22, 0x29,
	0x0a, 0x08, 0x44, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x22, 0x3f, 0x0a, 0x08, 0x44, 0x72, 0x61,
	0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x15, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f,
	0x6d, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0xb4, 0x01, 0x0a, 0x0d,
	0x43, 0x6f, 0x6d, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2d, 0x0a,
	0x12, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x70, 0x75, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x63, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x32, 0xc3, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x50, 0x75,
	0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04,
	0x4b, 0x69, 0x63, 0x6b, 0x12, 0x0c, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x73, 0x70,
	0x12, 0x25, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x79, 0x69, 0x6d, 0x2e,
	0x44, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x44,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x73, 0x70, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6d, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78,
	0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x79, 0x69, 0x6d, 0x3b, 0x79, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_comet_proto_rawDescOnce sync.Once
	file_service_comet_proto_rawDescData = file_service_comet_proto_rawDesc
)

func file_service_comet_proto_rawDescGZIP() []byte {
	file_service_comet_proto_rawDescOnce.Do(func() {
		file_service_comet_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_comet_proto_rawDescData)
	})
	return file_service_comet_proto_rawDescData
}

var file_service_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_comet_proto_goTypes = []interface{}{
	(*PushMessageReq)(nil), // 0: yim.PushMessageReq
	(*PushMessageRsp)(nil), // 1: yim.PushMessageRsp
	(*KickReq)(nil),        // 2: yim.KickReq
	(*KickRsp)(nil),        // 3: yim.KickRsp
	(*DrainReq)(nil),       // 4: yim.DrainReq
	(*DrainRsp)(nil),       // 5: yim.DrainRsp
	(*CometStatsReq)(nil),  // 6: yim.CometStatsReq
	(*CometStatsRsp)(nil),  // 7: yim.CometStatsRsp
}
var file_service_comet_proto_depIdxs = []int32{
	0, // 0: yim.CometService.PushMessage:input_type -> yim.PushMessageReq
	2, // 1: yim.CometService.Kick:input_type -> yim.KickReq
	4, // 2: yim.CometService.Drain:input_type -> yim.DrainReq
	6, // 3: yim.CometService.Stats:input_type -> yim.CometStatsReq
	1, // 4: yim.CometService.PushMessage:output_type -> yim.PushMessageRsp
	3, // 5: yim.CometService.Kick:output_type -> yim.KickRsp
	5, // 6: yim.CometService.Drain:output_type -> yim.DrainRsp
	7, // 7: yim.CometService.Stats:output_type -> yim.CometStatsRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_comet_proto_init() }
func file_service_comet_proto_init() {
	if File_service_comet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_comet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_comet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMessageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_comet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_comet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_comet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_comet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrainRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_comet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CometStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_comet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CometStatsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_comet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_comet_proto_goTypes,
		DependencyIndexes: file_service_comet_proto_depIdxs,
		MessageInfos:      file_service_comet_proto_msgTypes,
	}.Build()
	File_service_comet_proto = out.File
	file_service_comet_proto_rawDesc = nil
	file_service_comet_proto_goTypes = nil
	file_service_comet_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.16.3. DO NOT EDIT.

type CometService interface {
	PushMessage(ctx context.Context, req *PushMessageReq) (res *PushMessageRsp, err error)
	Kick(ctx context.Context, req *KickReq) (res *KickRsp, err error)
	Drain(ctx context.Context, req *DrainReq) (res *DrainRsp, err error)
	Stats(ctx context.Context, req *CometStatsReq) (res *CometStatsRsp, err error)
}
