// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: service_seq.proto

package yim

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz   string `protobuf:"bytes,1,opt,name=biz,proto3" json:"biz,omitempty"`                   // uid / msg / conv_id ...
	KeyId int64  `protobuf:"varint,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // 分片键, 实体 ID 固定 0
	Count int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *AllocIdReq) Reset() {
	*x = AllocIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIdReq) ProtoMessage() {}

func (x *AllocIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIdReq.ProtoReflect.Descriptor instead.
func (*AllocIdReq) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{0}
}

func (x *AllocIdReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *AllocIdReq) GetKeyId() int64 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *AllocIdReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AllocIdRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // 分配区间 [start, start+count-1]
}

func (x *AllocIdRsp) Reset() {
	*x = AllocIdRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocIdRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIdRsp) ProtoMessage() {}

func (x *AllocIdRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIdRsp.ProtoReflect.Descriptor instead.
func (*AllocIdRsp) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{1}
}

func (x *AllocIdRsp) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

type AllocConvSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Count  int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 一次批量申请数, 预留群聊合并写场景
}

func (x *AllocConvSeqReq) Reset() {
	*x = AllocConvSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocConvSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocConvSeqReq) ProtoMessage() {}

func (x *AllocConvSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocConvSeqReq.ProtoReflect.Descriptor instead.
func (*AllocConvSeqReq) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{2}
}

func (x *AllocConvSeqReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *AllocConvSeqReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AllocConvSeqRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // 分配区间 [start, start+count-1]
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *AllocConvSeqRsp) Reset() {
	*x = AllocConvSeqRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocConvSeqRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocConvSeqRsp) ProtoMessage() {}

func (x *AllocConvSeqRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocConvSeqRsp.ProtoReflect.Descriptor instead.
func (*AllocConvSeqRsp) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{3}
}

func (x *AllocConvSeqRsp) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AllocConvSeqRsp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BumpSyncSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *BumpSyncSeqReq) Reset() {
	*x = BumpSyncSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BumpSyncSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpSyncSeqReq) ProtoMessage() {}

func (x *BumpSyncSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpSyncSeqReq.ProtoReflect.Descriptor instead.
func (*BumpSyncSeqReq) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{4}
}

func (x *BumpSyncSeqReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type BumpSyncSeqRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncSeq int64 `protobuf:"varint,1,opt,name=sync_seq,json=syncSeq,proto3" json:"sync_seq,omitempty"` // 递增后的新水位
}

func (x *BumpSyncSeqRsp) Reset() {
	*x = BumpSyncSeqRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BumpSyncSeqRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpSyncSeqRsp) ProtoMessage() {}

func (x *BumpSyncSeqRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpSyncSeqRsp.ProtoReflect.Descriptor instead.
func (*BumpSyncSeqRsp) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{5}
}

func (x *BumpSyncSeqRsp) GetSyncSeq() int64 {
	if x != nil {
		return x.SyncSeq
	}
	return 0
}

type GetSyncSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetSyncSeqReq) Reset() {
	*x = GetSyncSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSyncSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncSeqReq) ProtoMessage() {}

func (x *GetSyncSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncSeqReq.ProtoReflect.Descriptor instead.
func (*GetSyncSeqReq) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{6}
}

func (x *GetSyncSeqReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetSyncSeqRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncSeq int64 `protobuf:"varint,1,opt,name=sync_seq,json=syncSeq,proto3" json:"sync_seq,omitempty"`
}

func (x *GetSyncSeqRsp) Reset() {
	*x = GetSyncSeqRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSyncSeqRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncSeqRsp) ProtoMessage() {}

func (x *GetSyncSeqRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncSeqRsp.ProtoReflect.Descriptor instead.
func (*GetSyncSeqRsp) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{7}
}

func (x *GetSyncSeqRsp) GetSyncSeq() int64 {
	if x != nil {
		return x.SyncSeq
	}
	return 0
}

type InitConvReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvId int64 `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
}

func (x *InitConvReq) Reset() {
	*x = InitConvReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitConvReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConvReq) ProtoMessage() {}

func (x *InitConvReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConvReq.ProtoReflect.Descriptor instead.
func (*InitConvReq) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{8}
}

func (x *InitConvReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

type InitConvRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitConvRsp) Reset() {
	*x = InitConvRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_seq_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitConvRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConvRsp) ProtoMessage() {}

func (x *InitConvRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_seq_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConvRsp.ProtoReflect.Descriptor instead.
func (*InitConvRsp) Descriptor() ([]byte, []int) {
	return file_service_seq_proto_rawDescGZIP(), []int{9}
}

var File_service_seq_proto protoreflect.FileDescriptor

var file_service_seq_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x71, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x69, 0x6d, 0x22, 0x4b, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x6f,
	0x63, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x7a, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x7a, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x64,
	0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x40, 0x0a, 0x0f, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x43, 0x6f, 0x6e, 0x76, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x0f, 0x41,
	0x6c, 0x6c, 0x6f, 0x63, 0x43, 0x6f, 0x6e, 0x76, 0x53, 0x65, 0x71, 0x52, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x0e, 0x42, 0x75,
	0x6d, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2b,
	0x0a, 0x0e, 0x42, 0x75, 0x6d, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x52, 0x73, 0x70,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x22, 0x21, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2a,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x52, 0x73, 0x70, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x22, 0x26, 0x0a, 0x0b, 0x49, 0x6e,
	0x69, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x76, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76,
	0x49, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x52, 0x73,
	0x70, 0x32, 0x94, 0x02, 0x0a, 0x0a, 0x53, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x2b, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x0f, 0x2e, 0x79, 0x69,
	0x6d, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x79,
	0x69, 0x6d, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x64, 0x52, 0x73, 0x70, 0x12, 0x3a, 0x0a,
	0x0c, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x43, 0x6f, 0x6e, 0x76, 0x53, 0x65, 0x71, 0x12, 0x14, 0x2e,
	0x79, 0x69, 0x6d, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x43, 0x6f, 0x6e, 0x76, 0x53, 0x65, 0x71,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x43,
	0x6f, 0x6e, 0x76, 0x53, 0x65, 0x71, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0b, 0x42, 0x75, 0x6d,
	0x70, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x12, 0x13, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x42,
	0x75, 0x6d, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x79, 0x69, 0x6d, 0x2e, 0x42, 0x75, 0x6d, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71, 0x52,
	0x73, 0x70, 0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x71,
	0x12, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65,
	0x71, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79,
	0x6e, 0x63, 0x53, 0x65, 0x71, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x49, 0x6e, 0x69, 0x74,
	0x43, 0x6f, 0x6e, 0x76, 0x12, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x43,
	0x6f, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x79, 0x69, 0x6d, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x43, 0x6f, 0x6e, 0x76, 0x52, 0x73, 0x70, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x69, 0x6d, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78,
	0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x79, 0x69, 0x6d, 0x3b, 0x79, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_seq_proto_rawDescOnce sync.Once
	file_service_seq_proto_rawDescData = file_service_seq_proto_rawDesc
)

func file_service_seq_proto_rawDescGZIP() []byte {
	file_service_seq_proto_rawDescOnce.Do(func() {
		file_service_seq_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_seq_proto_rawDescData)
	})
	return file_service_seq_proto_rawDescData
}

var file_service_seq_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_seq_proto_goTypes = []interface{}{
	(*AllocIdReq)(nil),      // 0: yim.AllocIdReq
	(*AllocIdRsp)(nil),      // 1: yim.AllocIdRsp
	(*AllocConvSeqReq)(nil), // 2: yim.AllocConvSeqReq
	(*AllocConvSeqRsp)(nil), // 3: yim.AllocConvSeqRsp
	(*BumpSyncSeqReq)(nil),  // 4: yim.BumpSyncSeqReq
	(*BumpSyncSeqRsp)(nil),  // 5: yim.BumpSyncSeqRsp
	(*GetSyncSeqReq)(nil),   // 6: yim.GetSyncSeqReq
	(*GetSyncSeqRsp)(nil),   // 7: yim.GetSyncSeqRsp
	(*InitConvReq)(nil),     // 8: yim.InitConvReq
	(*InitConvRsp)(nil),     // 9: yim.InitConvRsp
}
var file_service_seq_proto_depIdxs = []int32{
	0, // 0: yim.SeqService.AllocId:input_type -> yim.AllocIdReq
	2, // 1: yim.SeqService.AllocConvSeq:input_type -> yim.AllocConvSeqReq
	4, // 2: yim.SeqService.BumpSyncSeq:input_type -> yim.BumpSyncSeqReq
	6, // 3: yim.SeqService.GetSyncSeq:input_type -> yim.GetSyncSeqReq
	8, // 4: yim.SeqService.InitConv:input_type -> yim.InitConvReq
	1, // 5: yim.SeqService.AllocId:output_type -> yim.AllocIdRsp
	3, // 6: yim.SeqService.AllocConvSeq:output_type -> yim.AllocConvSeqRsp
	5, // 7: yim.SeqService.BumpSyncSeq:output_type -> yim.BumpSyncSeqRsp
	7, // 8: yim.SeqService.GetSyncSeq:output_type -> yim.GetSyncSeqRsp
	9, // 9: yim.SeqService.InitConv:output_type -> yim.InitConvRsp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_seq_proto_init() }
func file_service_seq_proto_init() {
	if File_service_seq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_seq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocIdRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocConvSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocConvSeqRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BumpSyncSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BumpSyncSeqRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSyncSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSyncSeqRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitConvReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_seq_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitConvRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_seq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_seq_proto_goTypes,
		DependencyIndexes: file_service_seq_proto_depIdxs,
		MessageInfos:      file_service_seq_proto_msgTypes,
	}.Build()
	File_service_seq_proto = out.File
	file_service_seq_proto_rawDesc = nil
	file_service_seq_proto_goTypes = nil
	file_service_seq_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.16.3. DO NOT EDIT.

type SeqService interface {
	AllocId(ctx context.Context, req *AllocIdReq) (res *AllocIdRsp, err error)
	AllocConvSeq(ctx context.Context, req *AllocConvSeqReq) (res *AllocConvSeqRsp, err error)
	BumpSyncSeq(ctx context.Context, req *BumpSyncSeqReq) (res *BumpSyncSeqRsp, err error)
	GetSyncSeq(ctx context.Context, req *GetSyncSeqReq) (res *GetSyncSeqRsp, err error)
	InitConv(ctx context.Context, req *InitConvReq) (res *InitConvRsp, err error)
}
