// Code generated by Kitex v0.16.3. DO NOT EDIT.

package seqservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	yim "github.com/yim/kitex_gen/yim"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AllocId": kitex.NewMethodInfo(
		allocIdHandler,
		newAllocIdArgs,
		newAllocIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AllocConvSeq": kitex.NewMethodInfo(
		allocConvSeqHandler,
		newAllocConvSeqArgs,
		newAllocConvSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BumpSyncSeq": kitex.NewMethodInfo(
		bumpSyncSeqHandler,
		newBumpSyncSeqArgs,
		newBumpSyncSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetSyncSeq": kitex.NewMethodInfo(
		getSyncSeqHandler,
		newGetSyncSeqArgs,
		newGetSyncSeqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"InitConv": kitex.NewMethodInfo(
		initConvHandler,
		newInitConvArgs,
		newInitConvResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	seqServiceServiceInfo                = NewServiceInfo()
	seqServiceServiceInfoForClient       = NewServiceInfoForClient()
	seqServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return seqServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return seqServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return seqServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SeqService"
	handlerType := (*yim.SeqService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yim",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func allocIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.AllocIdReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.SeqService).AllocId(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AllocIdArgs:
		success, err := handler.(yim.SeqService).AllocId(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AllocIdResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAllocIdArgs() interface{} {
	return &AllocIdArgs{}
}

func newAllocIdResult() interface{} {
	return &AllocIdResult{}
}

type AllocIdArgs struct {
	Req *yim.AllocIdReq
}

func (p *AllocIdArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AllocIdArgs) Unmarshal(in []byte) error {
	msg := new(yim.AllocIdReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AllocIdArgs_Req_DEFAULT *yim.AllocIdReq

func (p *AllocIdArgs) GetReq() *yim.AllocIdReq {
	if !p.IsSetReq() {
		return AllocIdArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AllocIdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AllocIdArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AllocIdResult struct {
	Success *yim.AllocIdRsp
}

var AllocIdResult_Success_DEFAULT *yim.AllocIdRsp

func (p *AllocIdResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AllocIdResult) Unmarshal(in []byte) error {
	msg := new(yim.AllocIdRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AllocIdResult) GetSuccess() *yim.AllocIdRsp {
	if !p.IsSetSuccess() {
		return AllocIdResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AllocIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.AllocIdRsp)
}

func (p *AllocIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AllocIdResult) GetResult() interface{} {
	return p.Success
}

func allocConvSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.AllocConvSeqReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.SeqService).AllocConvSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AllocConvSeqArgs:
		success, err := handler.(yim.SeqService).AllocConvSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AllocConvSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAllocConvSeqArgs() interface{} {
	return &AllocConvSeqArgs{}
}

func newAllocConvSeqResult() interface{} {
	return &AllocConvSeqResult{}
}

type AllocConvSeqArgs struct {
	Req *yim.AllocConvSeqReq
}

func (p *AllocConvSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AllocConvSeqArgs) Unmarshal(in []byte) error {
	msg := new(yim.AllocConvSeqReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AllocConvSeqArgs_Req_DEFAULT *yim.AllocConvSeqReq

func (p *AllocConvSeqArgs) GetReq() *yim.AllocConvSeqReq {
	if !p.IsSetReq() {
		return AllocConvSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AllocConvSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AllocConvSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AllocConvSeqResult struct {
	Success *yim.AllocConvSeqRsp
}

var AllocConvSeqResult_Success_DEFAULT *yim.AllocConvSeqRsp

func (p *AllocConvSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AllocConvSeqResult) Unmarshal(in []byte) error {
	msg := new(yim.AllocConvSeqRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AllocConvSeqResult) GetSuccess() *yim.AllocConvSeqRsp {
	if !p.IsSetSuccess() {
		return AllocConvSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AllocConvSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.AllocConvSeqRsp)
}

func (p *AllocConvSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AllocConvSeqResult) GetResult() interface{} {
	return p.Success
}

func bumpSyncSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.BumpSyncSeqReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.SeqService).BumpSyncSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BumpSyncSeqArgs:
		success, err := handler.(yim.SeqService).BumpSyncSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BumpSyncSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBumpSyncSeqArgs() interface{} {
	return &BumpSyncSeqArgs{}
}

func newBumpSyncSeqResult() interface{} {
	return &BumpSyncSeqResult{}
}

type BumpSyncSeqArgs struct {
	Req *yim.BumpSyncSeqReq
}

func (p *BumpSyncSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BumpSyncSeqArgs) Unmarshal(in []byte) error {
	msg := new(yim.BumpSyncSeqReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BumpSyncSeqArgs_Req_DEFAULT *yim.BumpSyncSeqReq

func (p *BumpSyncSeqArgs) GetReq() *yim.BumpSyncSeqReq {
	if !p.IsSetReq() {
		return BumpSyncSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BumpSyncSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BumpSyncSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BumpSyncSeqResult struct {
	Success *yim.BumpSyncSeqRsp
}

var BumpSyncSeqResult_Success_DEFAULT *yim.BumpSyncSeqRsp

func (p *BumpSyncSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BumpSyncSeqResult) Unmarshal(in []byte) error {
	msg := new(yim.BumpSyncSeqRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BumpSyncSeqResult) GetSuccess() *yim.BumpSyncSeqRsp {
	if !p.IsSetSuccess() {
		return BumpSyncSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BumpSyncSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.BumpSyncSeqRsp)
}

func (p *BumpSyncSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BumpSyncSeqResult) GetResult() interface{} {
	return p.Success
}

func getSyncSeqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.GetSyncSeqReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.SeqService).GetSyncSeq(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSyncSeqArgs:
		success, err := handler.(yim.SeqService).GetSyncSeq(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSyncSeqResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSyncSeqArgs() interface{} {
	return &GetSyncSeqArgs{}
}

func newGetSyncSeqResult() interface{} {
	return &GetSyncSeqResult{}
}

type GetSyncSeqArgs struct {
	Req *yim.GetSyncSeqReq
}

func (p *GetSyncSeqArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSyncSeqArgs) Unmarshal(in []byte) error {
	msg := new(yim.GetSyncSeqReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSyncSeqArgs_Req_DEFAULT *yim.GetSyncSeqReq

func (p *GetSyncSeqArgs) GetReq() *yim.GetSyncSeqReq {
	if !p.IsSetReq() {
		return GetSyncSeqArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSyncSeqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSyncSeqArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSyncSeqResult struct {
	Success *yim.GetSyncSeqRsp
}

var GetSyncSeqResult_Success_DEFAULT *yim.GetSyncSeqRsp

func (p *GetSyncSeqResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSyncSeqResult) Unmarshal(in []byte) error {
	msg := new(yim.GetSyncSeqRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSyncSeqResult) GetSuccess() *yim.GetSyncSeqRsp {
	if !p.IsSetSuccess() {
		return GetSyncSeqResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSyncSeqResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.GetSyncSeqRsp)
}

func (p *GetSyncSeqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSyncSeqResult) GetResult() interface{} {
	return p.Success
}

func initConvHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.InitConvReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.SeqService).InitConv(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *InitConvArgs:
		success, err := handler.(yim.SeqService).InitConv(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*InitConvResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newInitConvArgs() interface{} {
	return &InitConvArgs{}
}

func newInitConvResult() interface{} {
	return &InitConvResult{}
}

type InitConvArgs struct {
	Req *yim.InitConvReq
}

func (p *InitConvArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *InitConvArgs) Unmarshal(in []byte) error {
	msg := new(yim.InitConvReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var InitConvArgs_Req_DEFAULT *yim.InitConvReq

func (p *InitConvArgs) GetReq() *yim.InitConvReq {
	if !p.IsSetReq() {
		return InitConvArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *InitConvArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InitConvArgs) GetFirstArgument() interface{} {
	return p.Req
}

type InitConvResult struct {
	Success *yim.InitConvRsp
}

var InitConvResult_Success_DEFAULT *yim.InitConvRsp

func (p *InitConvResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *InitConvResult) Unmarshal(in []byte) error {
	msg := new(yim.InitConvRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *InitConvResult) GetSuccess() *yim.InitConvRsp {
	if !p.IsSetSuccess() {
		return InitConvResult_Success_DEFAULT
	}
	return p.Success
}

func (p *InitConvResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.InitConvRsp)
}

func (p *InitConvResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InitConvResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AllocId(ctx context.Context, Req *yim.AllocIdReq) (r *yim.AllocIdRsp, err error) {
	var _args AllocIdArgs
	_args.Req = Req
	var _result AllocIdResult
	if err = p.c.Call(ctx, "AllocId", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AllocConvSeq(ctx context.Context, Req *yim.AllocConvSeqReq) (r *yim.AllocConvSeqRsp, err error) {
	var _args AllocConvSeqArgs
	_args.Req = Req
	var _result AllocConvSeqResult
	if err = p.c.Call(ctx, "AllocConvSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BumpSyncSeq(ctx context.Context, Req *yim.BumpSyncSeqReq) (r *yim.BumpSyncSeqRsp, err error) {
	var _args BumpSyncSeqArgs
	_args.Req = Req
	var _result BumpSyncSeqResult
	if err = p.c.Call(ctx, "BumpSyncSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSyncSeq(ctx context.Context, Req *yim.GetSyncSeqReq) (r *yim.GetSyncSeqRsp, err error) {
	var _args GetSyncSeqArgs
	_args.Req = Req
	var _result GetSyncSeqResult
	if err = p.c.Call(ctx, "GetSyncSeq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InitConv(ctx context.Context, Req *yim.InitConvReq) (r *yim.InitConvRsp, err error) {
	var _args InitConvArgs
	_args.Req = Req
	var _result InitConvResult
	if err = p.c.Call(ctx, "InitConv", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
