// Code generated by Kitex v0.16.3. DO NOT EDIT.

package relationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	yim "github.com/yim/kitex_gen/yim"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendFriendRequest(ctx context.Context, Req *yim.SendFriendRequestReq, callOptions ...callopt.Option) (r *yim.SendFriendRequestRsp, err error)
	HandleFriendRequest(ctx context.Context, Req *yim.HandleFriendRequestReq, callOptions ...callopt.Option) (r *yim.HandleFriendRequestRsp, err error)
	ListFriendRequests(ctx context.Context, Req *yim.ListFriendRequestsReq, callOptions ...callopt.Option) (r *yim.ListFriendRequestsRsp, err error)
	ListFriends(ctx context.Context, Req *yim.ListFriendsReq, callOptions ...callopt.Option) (r *yim.ListFriendsRsp, err error)
	DeleteFriend(ctx context.Context, Req *yim.DeleteFriendReq, callOptions ...callopt.Option) (r *yim.DeleteFriendRsp, err error)
	CheckFriendship(ctx context.Context, Req *yim.CheckFriendshipReq, callOptions ...callopt.Option) (r *yim.CheckFriendshipRsp, err error)
	AddGroupMembers(ctx context.Context, Req *yim.AddGroupMembersReq, callOptions ...callopt.Option) (r *yim.AddGroupMembersRsp, err error)
	RemoveGroupMember(ctx context.Context, Req *yim.RemoveGroupMemberReq, callOptions ...callopt.Option) (r *yim.RemoveGroupMemberRsp, err error)
	QuitGroup(ctx context.Context, Req *yim.QuitGroupReq, callOptions ...callopt.Option) (r *yim.QuitGroupRsp, err error)
	ListGroupMembers(ctx context.Context, Req *yim.ListGroupMembersReq, callOptions ...callopt.Option) (r *yim.ListGroupMembersRsp, err error)
	UpdateGroupInfo(ctx context.Context, Req *yim.UpdateGroupInfoReq, callOptions ...callopt.Option) (r *yim.UpdateGroupInfoRsp, err error)
	GetProfiles(ctx context.Context, Req *yim.GetProfilesReq, callOptions ...callopt.Option) (r *yim.GetProfilesRsp, err error)
	SearchUsers(ctx context.Context, Req *yim.SearchUsersReq, callOptions ...callopt.Option) (r *yim.SearchUsersRsp, err error)
	UpdateProfile(ctx context.Context, Req *yim.UpdateProfileReq, callOptions ...callopt.Option) (r *yim.UpdateProfileRsp, err error)
	GetPresence(ctx context.Context, Req *yim.GetPresenceReq, callOptions ...callopt.Option) (r *yim.GetPresenceRsp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) SendFriendRequest(ctx context.Context, Req *yim.SendFriendRequestReq, callOptions ...callopt.Option) (r *yim.SendFriendRequestRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendFriendRequest(ctx, Req)
}

func (p *kRelationServiceClient) HandleFriendRequest(ctx context.Context, Req *yim.HandleFriendRequestReq, callOptions ...callopt.Option) (r *yim.HandleFriendRequestRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HandleFriendRequest(ctx, Req)
}

func (p *kRelationServiceClient) ListFriendRequests(ctx context.Context, Req *yim.ListFriendRequestsReq, callOptions ...callopt.Option) (r *yim.ListFriendRequestsRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriendRequests(ctx, Req)
}

func (p *kRelationServiceClient) ListFriends(ctx context.Context, Req *yim.ListFriendsReq, callOptions ...callopt.Option) (r *yim.ListFriendsRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriends(ctx, Req)
}

func (p *kRelationServiceClient) DeleteFriend(ctx context.Context, Req *yim.DeleteFriendReq, callOptions ...callopt.Option) (r *yim.DeleteFriendRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFriend(ctx, Req)
}

func (p *kRelationServiceClient) CheckFriendship(ctx context.Context, Req *yim.CheckFriendshipReq, callOptions ...callopt.Option) (r *yim.CheckFriendshipRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckFriendship(ctx, Req)
}

func (p *kRelationServiceClient) AddGroupMembers(ctx context.Context, Req *yim.AddGroupMembersReq, callOptions ...callopt.Option) (r *yim.AddGroupMembersRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddGroupMembers(ctx, Req)
}

func (p *kRelationServiceClient) RemoveGroupMember(ctx context.Context, Req *yim.RemoveGroupMemberReq, callOptions ...callopt.Option) (r *yim.RemoveGroupMemberRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveGroupMember(ctx, Req)
}

func (p *kRelationServiceClient) QuitGroup(ctx context.Context, Req *yim.QuitGroupReq, callOptions ...callopt.Option) (r *yim.QuitGroupRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QuitGroup(ctx, Req)
}

func (p *kRelationServiceClient) ListGroupMembers(ctx context.Context, Req *yim.ListGroupMembersReq, callOptions ...callopt.Option) (r *yim.ListGroupMembersRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListGroupMembers(ctx, Req)
}

func (p *kRelationServiceClient) UpdateGroupInfo(ctx context.Context, Req *yim.UpdateGroupInfoReq, callOptions ...callopt.Option) (r *yim.UpdateGroupInfoRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateGroupInfo(ctx, Req)
}

func (p *kRelationServiceClient) GetProfiles(ctx context.Context, Req *yim.GetProfilesReq, callOptions ...callopt.Option) (r *yim.GetProfilesRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProfiles(ctx, Req)
}

func (p *kRelationServiceClient) SearchUsers(ctx context.Context, Req *yim.SearchUsersReq, callOptions ...callopt.Option) (r *yim.SearchUsersRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchUsers(ctx, Req)
}

func (p *kRelationServiceClient) UpdateProfile(ctx context.Context, Req *yim.UpdateProfileReq, callOptions ...callopt.Option) (r *yim.UpdateProfileRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProfile(ctx, Req)
}

func (p *kRelationServiceClient) GetPresence(ctx context.Context, Req *yim.GetPresenceReq, callOptions ...callopt.Option) (r *yim.GetPresenceRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPresence(ctx, Req)
}
