// Code generated by Kitex v0.16.3. DO NOT EDIT.

package relationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	yim "github.com/yim/kitex_gen/yim"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendFriendRequest": kitex.NewMethodInfo(
		sendFriendRequestHandler,
		newSendFriendRequestArgs,
		newSendFriendRequestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"HandleFriendRequest": kitex.NewMethodInfo(
		handleFriendRequestHandler,
		newHandleFriendRequestArgs,
		newHandleFriendRequestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListFriendRequests": kitex.NewMethodInfo(
		listFriendRequestsHandler,
		newListFriendRequestsArgs,
		newListFriendRequestsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListFriends": kitex.NewMethodInfo(
		listFriendsHandler,
		newListFriendsArgs,
		newListFriendsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteFriend": kitex.NewMethodInfo(
		deleteFriendHandler,
		newDeleteFriendArgs,
		newDeleteFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CheckFriendship": kitex.NewMethodInfo(
		checkFriendshipHandler,
		newCheckFriendshipArgs,
		newCheckFriendshipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddGroupMembers": kitex.NewMethodInfo(
		addGroupMembersHandler,
		newAddGroupMembersArgs,
		newAddGroupMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RemoveGroupMember": kitex.NewMethodInfo(
		removeGroupMemberHandler,
		newRemoveGroupMemberArgs,
		newRemoveGroupMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"QuitGroup": kitex.NewMethodInfo(
		quitGroupHandler,
		newQuitGroupArgs,
		newQuitGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListGroupMembers": kitex.NewMethodInfo(
		listGroupMembersHandler,
		newListGroupMembersArgs,
		newListGroupMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateGroupInfo": kitex.NewMethodInfo(
		updateGroupInfoHandler,
		newUpdateGroupInfoArgs,
		newUpdateGroupInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetProfiles": kitex.NewMethodInfo(
		getProfilesHandler,
		newGetProfilesArgs,
		newGetProfilesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchUsers": kitex.NewMethodInfo(
		searchUsersHandler,
		newSearchUsersArgs,
		newSearchUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateProfile": kitex.NewMethodInfo(
		updateProfileHandler,
		newUpdateProfileArgs,
		newUpdateProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPresence": kitex.NewMethodInfo(
		getPresenceHandler,
		newGetPresenceArgs,
		newGetPresenceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	relationServiceServiceInfo                = NewServiceInfo()
	relationServiceServiceInfoForClient       = NewServiceInfoForClient()
	relationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return relationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return relationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return relationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RelationService"
	handlerType := (*yim.RelationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yim",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func sendFriendRequestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.SendFriendRequestReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).SendFriendRequest(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SendFriendRequestArgs:
		success, err := handler.(yim.RelationService).SendFriendRequest(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SendFriendRequestResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSendFriendRequestArgs() interface{} {
	return &SendFriendRequestArgs{}
}

func newSendFriendRequestResult() interface{} {
	return &SendFriendRequestResult{}
}

type SendFriendRequestArgs struct {
	Req *yim.SendFriendRequestReq
}

func (p *SendFriendRequestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SendFriendRequestArgs) Unmarshal(in []byte) error {
	msg := new(yim.SendFriendRequestReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SendFriendRequestArgs_Req_DEFAULT *yim.SendFriendRequestReq

func (p *SendFriendRequestArgs) GetReq() *yim.SendFriendRequestReq {
	if !p.IsSetReq() {
		return SendFriendRequestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SendFriendRequestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SendFriendRequestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SendFriendRequestResult struct {
	Success *yim.SendFriendRequestRsp
}

var SendFriendRequestResult_Success_DEFAULT *yim.SendFriendRequestRsp

func (p *SendFriendRequestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SendFriendRequestResult) Unmarshal(in []byte) error {
	msg := new(yim.SendFriendRequestRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SendFriendRequestResult) GetSuccess() *yim.SendFriendRequestRsp {
	if !p.IsSetSuccess() {
		return SendFriendRequestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SendFriendRequestResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.SendFriendRequestRsp)
}

func (p *SendFriendRequestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SendFriendRequestResult) GetResult() interface{} {
	return p.Success
}

func handleFriendRequestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.HandleFriendRequestReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).HandleFriendRequest(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HandleFriendRequestArgs:
		success, err := handler.(yim.RelationService).HandleFriendRequest(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HandleFriendRequestResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHandleFriendRequestArgs() interface{} {
	return &HandleFriendRequestArgs{}
}

func newHandleFriendRequestResult() interface{} {
	return &HandleFriendRequestResult{}
}

type HandleFriendRequestArgs struct {
	Req *yim.HandleFriendRequestReq
}

func (p *HandleFriendRequestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HandleFriendRequestArgs) Unmarshal(in []byte) error {
	msg := new(yim.HandleFriendRequestReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HandleFriendRequestArgs_Req_DEFAULT *yim.HandleFriendRequestReq

func (p *HandleFriendRequestArgs) GetReq() *yim.HandleFriendRequestReq {
	if !p.IsSetReq() {
		return HandleFriendRequestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HandleFriendRequestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HandleFriendRequestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HandleFriendRequestResult struct {
	Success *yim.HandleFriendRequestRsp
}

var HandleFriendRequestResult_Success_DEFAULT *yim.HandleFriendRequestRsp

func (p *HandleFriendRequestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HandleFriendRequestResult) Unmarshal(in []byte) error {
	msg := new(yim.HandleFriendRequestRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HandleFriendRequestResult) GetSuccess() *yim.HandleFriendRequestRsp {
	if !p.IsSetSuccess() {
		return HandleFriendRequestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HandleFriendRequestResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.HandleFriendRequestRsp)
}

func (p *HandleFriendRequestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HandleFriendRequestResult) GetResult() interface{} {
	return p.Success
}

func listFriendRequestsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.ListFriendRequestsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).ListFriendRequests(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListFriendRequestsArgs:
		success, err := handler.(yim.RelationService).ListFriendRequests(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListFriendRequestsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListFriendRequestsArgs() interface{} {
	return &ListFriendRequestsArgs{}
}

func newListFriendRequestsResult() interface{} {
	return &ListFriendRequestsResult{}
}

type ListFriendRequestsArgs struct {
	Req *yim.ListFriendRequestsReq
}

func (p *ListFriendRequestsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListFriendRequestsArgs) Unmarshal(in []byte) error {
	msg := new(yim.ListFriendRequestsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListFriendRequestsArgs_Req_DEFAULT *yim.ListFriendRequestsReq

func (p *ListFriendRequestsArgs) GetReq() *yim.ListFriendRequestsReq {
	if !p.IsSetReq() {
		return ListFriendRequestsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListFriendRequestsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListFriendRequestsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListFriendRequestsResult struct {
	Success *yim.ListFriendRequestsRsp
}

var ListFriendRequestsResult_Success_DEFAULT *yim.ListFriendRequestsRsp

func (p *ListFriendRequestsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListFriendRequestsResult) Unmarshal(in []byte) error {
	msg := new(yim.ListFriendRequestsRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListFriendRequestsResult) GetSuccess() *yim.ListFriendRequestsRsp {
	if !p.IsSetSuccess() {
		return ListFriendRequestsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListFriendRequestsResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.ListFriendRequestsRsp)
}

func (p *ListFriendRequestsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListFriendRequestsResult) GetResult() interface{} {
	return p.Success
}

func listFriendsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.ListFriendsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).ListFriends(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListFriendsArgs:
		success, err := handler.(yim.RelationService).ListFriends(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListFriendsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListFriendsArgs() interface{} {
	return &ListFriendsArgs{}
}

func newListFriendsResult() interface{} {
	return &ListFriendsResult{}
}

type ListFriendsArgs struct {
	Req *yim.ListFriendsReq
}

func (p *ListFriendsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListFriendsArgs) Unmarshal(in []byte) error {
	msg := new(yim.ListFriendsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListFriendsArgs_Req_DEFAULT *yim.ListFriendsReq

func (p *ListFriendsArgs) GetReq() *yim.ListFriendsReq {
	if !p.IsSetReq() {
		return ListFriendsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListFriendsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListFriendsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListFriendsResult struct {
	Success *yim.ListFriendsRsp
}

var ListFriendsResult_Success_DEFAULT *yim.ListFriendsRsp

func (p *ListFriendsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListFriendsResult) Unmarshal(in []byte) error {
	msg := new(yim.ListFriendsRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListFriendsResult) GetSuccess() *yim.ListFriendsRsp {
	if !p.IsSetSuccess() {
		return ListFriendsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListFriendsResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.ListFriendsRsp)
}

func (p *ListFriendsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListFriendsResult) GetResult() interface{} {
	return p.Success
}

func deleteFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.DeleteFriendReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).DeleteFriend(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteFriendArgs:
		success, err := handler.(yim.RelationService).DeleteFriend(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteFriendResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteFriendArgs() interface{} {
	return &DeleteFriendArgs{}
}

func newDeleteFriendResult() interface{} {
	return &DeleteFriendResult{}
}

type DeleteFriendArgs struct {
	Req *yim.DeleteFriendReq
}

func (p *DeleteFriendArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteFriendArgs) Unmarshal(in []byte) error {
	msg := new(yim.DeleteFriendReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteFriendArgs_Req_DEFAULT *yim.DeleteFriendReq

func (p *DeleteFriendArgs) GetReq() *yim.DeleteFriendReq {
	if !p.IsSetReq() {
		return DeleteFriendArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteFriendArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteFriendResult struct {
	Success *yim.DeleteFriendRsp
}

var DeleteFriendResult_Success_DEFAULT *yim.DeleteFriendRsp

func (p *DeleteFriendResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteFriendResult) Unmarshal(in []byte) error {
	msg := new(yim.DeleteFriendRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteFriendResult) GetSuccess() *yim.DeleteFriendRsp {
	if !p.IsSetSuccess() {
		return DeleteFriendResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.DeleteFriendRsp)
}

func (p *DeleteFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteFriendResult) GetResult() interface{} {
	return p.Success
}

func checkFriendshipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.CheckFriendshipReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).CheckFriendship(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckFriendshipArgs:
		success, err := handler.(yim.RelationService).CheckFriendship(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckFriendshipResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckFriendshipArgs() interface{} {
	return &CheckFriendshipArgs{}
}

func newCheckFriendshipResult() interface{} {
	return &CheckFriendshipResult{}
}

type CheckFriendshipArgs struct {
	Req *yim.CheckFriendshipReq
}

func (p *CheckFriendshipArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckFriendshipArgs) Unmarshal(in []byte) error {
	msg := new(yim.CheckFriendshipReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckFriendshipArgs_Req_DEFAULT *yim.CheckFriendshipReq

func (p *CheckFriendshipArgs) GetReq() *yim.CheckFriendshipReq {
	if !p.IsSetReq() {
		return CheckFriendshipArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckFriendshipArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckFriendshipArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckFriendshipResult struct {
	Success *yim.CheckFriendshipRsp
}

var CheckFriendshipResult_Success_DEFAULT *yim.CheckFriendshipRsp

func (p *CheckFriendshipResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckFriendshipResult) Unmarshal(in []byte) error {
	msg := new(yim.CheckFriendshipRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckFriendshipResult) GetSuccess() *yim.CheckFriendshipRsp {
	if !p.IsSetSuccess() {
		return CheckFriendshipResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckFriendshipResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.CheckFriendshipRsp)
}

func (p *CheckFriendshipResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckFriendshipResult) GetResult() interface{} {
	return p.Success
}

func addGroupMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.AddGroupMembersReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).AddGroupMembers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddGroupMembersArgs:
		success, err := handler.(yim.RelationService).AddGroupMembers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddGroupMembersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddGroupMembersArgs() interface{} {
	return &AddGroupMembersArgs{}
}

func newAddGroupMembersResult() interface{} {
	return &AddGroupMembersResult{}
}

type AddGroupMembersArgs struct {
	Req *yim.AddGroupMembersReq
}

func (p *AddGroupMembersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddGroupMembersArgs) Unmarshal(in []byte) error {
	msg := new(yim.AddGroupMembersReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddGroupMembersArgs_Req_DEFAULT *yim.AddGroupMembersReq

func (p *AddGroupMembersArgs) GetReq() *yim.AddGroupMembersReq {
	if !p.IsSetReq() {
		return AddGroupMembersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddGroupMembersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddGroupMembersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddGroupMembersResult struct {
	Success *yim.AddGroupMembersRsp
}

var AddGroupMembersResult_Success_DEFAULT *yim.AddGroupMembersRsp

func (p *AddGroupMembersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddGroupMembersResult) Unmarshal(in []byte) error {
	msg := new(yim.AddGroupMembersRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddGroupMembersResult) GetSuccess() *yim.AddGroupMembersRsp {
	if !p.IsSetSuccess() {
		return AddGroupMembersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddGroupMembersResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.AddGroupMembersRsp)
}

func (p *AddGroupMembersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddGroupMembersResult) GetResult() interface{} {
	return p.Success
}

func removeGroupMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.RemoveGroupMemberReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).RemoveGroupMember(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RemoveGroupMemberArgs:
		success, err := handler.(yim.RelationService).RemoveGroupMember(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RemoveGroupMemberResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRemoveGroupMemberArgs() interface{} {
	return &RemoveGroupMemberArgs{}
}

func newRemoveGroupMemberResult() interface{} {
	return &RemoveGroupMemberResult{}
}

type RemoveGroupMemberArgs struct {
	Req *yim.RemoveGroupMemberReq
}

func (p *RemoveGroupMemberArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RemoveGroupMemberArgs) Unmarshal(in []byte) error {
	msg := new(yim.RemoveGroupMemberReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RemoveGroupMemberArgs_Req_DEFAULT *yim.RemoveGroupMemberReq

func (p *RemoveGroupMemberArgs) GetReq() *yim.RemoveGroupMemberReq {
	if !p.IsSetReq() {
		return RemoveGroupMemberArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RemoveGroupMemberArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RemoveGroupMemberArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RemoveGroupMemberResult struct {
	Success *yim.RemoveGroupMemberRsp
}

var RemoveGroupMemberResult_Success_DEFAULT *yim.RemoveGroupMemberRsp

func (p *RemoveGroupMemberResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RemoveGroupMemberResult) Unmarshal(in []byte) error {
	msg := new(yim.RemoveGroupMemberRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RemoveGroupMemberResult) GetSuccess() *yim.RemoveGroupMemberRsp {
	if !p.IsSetSuccess() {
		return RemoveGroupMemberResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RemoveGroupMemberResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.RemoveGroupMemberRsp)
}

func (p *RemoveGroupMemberResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RemoveGroupMemberResult) GetResult() interface{} {
	return p.Success
}

func quitGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.QuitGroupReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).QuitGroup(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QuitGroupArgs:
		success, err := handler.(yim.RelationService).QuitGroup(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QuitGroupResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQuitGroupArgs() interface{} {
	return &QuitGroupArgs{}
}

func newQuitGroupResult() interface{} {
	return &QuitGroupResult{}
}

type QuitGroupArgs struct {
	Req *yim.QuitGroupReq
}

func (p *QuitGroupArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QuitGroupArgs) Unmarshal(in []byte) error {
	msg := new(yim.QuitGroupReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QuitGroupArgs_Req_DEFAULT *yim.QuitGroupReq

func (p *QuitGroupArgs) GetReq() *yim.QuitGroupReq {
	if !p.IsSetReq() {
		return QuitGroupArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QuitGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QuitGroupArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QuitGroupResult struct {
	Success *yim.QuitGroupRsp
}

var QuitGroupResult_Success_DEFAULT *yim.QuitGroupRsp

func (p *QuitGroupResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QuitGroupResult) Unmarshal(in []byte) error {
	msg := new(yim.QuitGroupRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QuitGroupResult) GetSuccess() *yim.QuitGroupRsp {
	if !p.IsSetSuccess() {
		return QuitGroupResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QuitGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.QuitGroupRsp)
}

func (p *QuitGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QuitGroupResult) GetResult() interface{} {
	return p.Success
}

func listGroupMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.ListGroupMembersReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).ListGroupMembers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListGroupMembersArgs:
		success, err := handler.(yim.RelationService).ListGroupMembers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListGroupMembersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListGroupMembersArgs() interface{} {
	return &ListGroupMembersArgs{}
}

func newListGroupMembersResult() interface{} {
	return &ListGroupMembersResult{}
}

type ListGroupMembersArgs struct {
	Req *yim.ListGroupMembersReq
}

func (p *ListGroupMembersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListGroupMembersArgs) Unmarshal(in []byte) error {
	msg := new(yim.ListGroupMembersReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListGroupMembersArgs_Req_DEFAULT *yim.ListGroupMembersReq

func (p *ListGroupMembersArgs) GetReq() *yim.ListGroupMembersReq {
	if !p.IsSetReq() {
		return ListGroupMembersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListGroupMembersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListGroupMembersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListGroupMembersResult struct {
	Success *yim.ListGroupMembersRsp
}

var ListGroupMembersResult_Success_DEFAULT *yim.ListGroupMembersRsp

func (p *ListGroupMembersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListGroupMembersResult) Unmarshal(in []byte) error {
	msg := new(yim.ListGroupMembersRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListGroupMembersResult) GetSuccess() *yim.ListGroupMembersRsp {
	if !p.IsSetSuccess() {
		return ListGroupMembersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListGroupMembersResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.ListGroupMembersRsp)
}

func (p *ListGroupMembersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListGroupMembersResult) GetResult() interface{} {
	return p.Success
}

func updateGroupInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.UpdateGroupInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).UpdateGroupInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateGroupInfoArgs:
		success, err := handler.(yim.RelationService).UpdateGroupInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateGroupInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateGroupInfoArgs() interface{} {
	return &UpdateGroupInfoArgs{}
}

func newUpdateGroupInfoResult() interface{} {
	return &UpdateGroupInfoResult{}
}

type UpdateGroupInfoArgs struct {
	Req *yim.UpdateGroupInfoReq
}

func (p *UpdateGroupInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateGroupInfoArgs) Unmarshal(in []byte) error {
	msg := new(yim.UpdateGroupInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateGroupInfoArgs_Req_DEFAULT *yim.UpdateGroupInfoReq

func (p *UpdateGroupInfoArgs) GetReq() *yim.UpdateGroupInfoReq {
	if !p.IsSetReq() {
		return UpdateGroupInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateGroupInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateGroupInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateGroupInfoResult struct {
	Success *yim.UpdateGroupInfoRsp
}

var UpdateGroupInfoResult_Success_DEFAULT *yim.UpdateGroupInfoRsp

func (p *UpdateGroupInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateGroupInfoResult) Unmarshal(in []byte) error {
	msg := new(yim.UpdateGroupInfoRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateGroupInfoResult) GetSuccess() *yim.UpdateGroupInfoRsp {
	if !p.IsSetSuccess() {
		return UpdateGroupInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateGroupInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.UpdateGroupInfoRsp)
}

func (p *UpdateGroupInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateGroupInfoResult) GetResult() interface{} {
	return p.Success
}

func getProfilesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.GetProfilesReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).GetProfiles(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetProfilesArgs:
		success, err := handler.(yim.RelationService).GetProfiles(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetProfilesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetProfilesArgs() interface{} {
	return &GetProfilesArgs{}
}

func newGetProfilesResult() interface{} {
	return &GetProfilesResult{}
}

type GetProfilesArgs struct {
	Req *yim.GetProfilesReq
}

func (p *GetProfilesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetProfilesArgs) Unmarshal(in []byte) error {
	msg := new(yim.GetProfilesReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetProfilesArgs_Req_DEFAULT *yim.GetProfilesReq

func (p *GetProfilesArgs) GetReq() *yim.GetProfilesReq {
	if !p.IsSetReq() {
		return GetProfilesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetProfilesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetProfilesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetProfilesResult struct {
	Success *yim.GetProfilesRsp
}

var GetProfilesResult_Success_DEFAULT *yim.GetProfilesRsp

func (p *GetProfilesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetProfilesResult) Unmarshal(in []byte) error {
	msg := new(yim.GetProfilesRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetProfilesResult) GetSuccess() *yim.GetProfilesRsp {
	if !p.IsSetSuccess() {
		return GetProfilesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetProfilesResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.GetProfilesRsp)
}

func (p *GetProfilesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetProfilesResult) GetResult() interface{} {
	return p.Success
}

func searchUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.SearchUsersReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).SearchUsers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchUsersArgs:
		success, err := handler.(yim.RelationService).SearchUsers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchUsersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchUsersArgs() interface{} {
	return &SearchUsersArgs{}
}

func newSearchUsersResult() interface{} {
	return &SearchUsersResult{}
}

type SearchUsersArgs struct {
	Req *yim.SearchUsersReq
}

func (p *SearchUsersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchUsersArgs) Unmarshal(in []byte) error {
	msg := new(yim.SearchUsersReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchUsersArgs_Req_DEFAULT *yim.SearchUsersReq

func (p *SearchUsersArgs) GetReq() *yim.SearchUsersReq {
	if !p.IsSetReq() {
		return SearchUsersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchUsersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchUsersResult struct {
	Success *yim.SearchUsersRsp
}

var SearchUsersResult_Success_DEFAULT *yim.SearchUsersRsp

func (p *SearchUsersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchUsersResult) Unmarshal(in []byte) error {
	msg := new(yim.SearchUsersRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchUsersResult) GetSuccess() *yim.SearchUsersRsp {
	if !p.IsSetSuccess() {
		return SearchUsersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.SearchUsersRsp)
}

func (p *SearchUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchUsersResult) GetResult() interface{} {
	return p.Success
}

func updateProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.UpdateProfileReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).UpdateProfile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateProfileArgs:
		success, err := handler.(yim.RelationService).UpdateProfile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateProfileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateProfileArgs() interface{} {
	return &UpdateProfileArgs{}
}

func newUpdateProfileResult() interface{} {
	return &UpdateProfileResult{}
}

type UpdateProfileArgs struct {
	Req *yim.UpdateProfileReq
}

func (p *UpdateProfileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateProfileArgs) Unmarshal(in []byte) error {
	msg := new(yim.UpdateProfileReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateProfileArgs_Req_DEFAULT *yim.UpdateProfileReq

func (p *UpdateProfileArgs) GetReq() *yim.UpdateProfileReq {
	if !p.IsSetReq() {
		return UpdateProfileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateProfileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateProfileResult struct {
	Success *yim.UpdateProfileRsp
}

var UpdateProfileResult_Success_DEFAULT *yim.UpdateProfileRsp

func (p *UpdateProfileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateProfileResult) Unmarshal(in []byte) error {
	msg := new(yim.UpdateProfileRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateProfileResult) GetSuccess() *yim.UpdateProfileRsp {
	if !p.IsSetSuccess() {
		return UpdateProfileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.UpdateProfileRsp)
}

func (p *UpdateProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateProfileResult) GetResult() interface{} {
	return p.Success
}

func getPresenceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(yim.GetPresenceReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(yim.RelationService).GetPresence(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPresenceArgs:
		success, err := handler.(yim.RelationService).GetPresence(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPresenceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPresenceArgs() interface{} {
	return &GetPresenceArgs{}
}

func newGetPresenceResult() interface{} {
	return &GetPresenceResult{}
}

type GetPresenceArgs struct {
	Req *yim.GetPresenceReq
}

func (p *GetPresenceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPresenceArgs) Unmarshal(in []byte) error {
	msg := new(yim.GetPresenceReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPresenceArgs_Req_DEFAULT *yim.GetPresenceReq

func (p *GetPresenceArgs) GetReq() *yim.GetPresenceReq {
	if !p.IsSetReq() {
		return GetPresenceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPresenceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPresenceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPresenceResult struct {
	Success *yim.GetPresenceRsp
}

var GetPresenceResult_Success_DEFAULT *yim.GetPresenceRsp

func (p *GetPresenceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPresenceResult) Unmarshal(in []byte) error {
	msg := new(yim.GetPresenceRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPresenceResult) GetSuccess() *yim.GetPresenceRsp {
	if !p.IsSetSuccess() {
		return GetPresenceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPresenceResult) SetSuccess(x interface{}) {
	p.Success = x.(*yim.GetPresenceRsp)
}

func (p *GetPresenceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPresenceResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendFriendRequest(ctx context.Context, Req *yim.SendFriendRequestReq) (r *yim.SendFriendRequestRsp, err error) {
	var _args SendFriendRequestArgs
	_args.Req = Req
	var _result SendFriendRequestResult
	if err = p.c.Call(ctx, "SendFriendRequest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HandleFriendRequest(ctx context.Context, Req *yim.HandleFriendRequestReq) (r *yim.HandleFriendRequestRsp, err error) {
	var _args HandleFriendRequestArgs
	_args.Req = Req
	var _result HandleFriendRequestResult
	if err = p.c.Call(ctx, "HandleFriendRequest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFriendRequests(ctx context.Context, Req *yim.ListFriendRequestsReq) (r *yim.ListFriendRequestsRsp, err error) {
	var _args ListFriendRequestsArgs
	_args.Req = Req
	var _result ListFriendRequestsResult
	if err = p.c.Call(ctx, "ListFriendRequests", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFriends(ctx context.Context, Req *yim.ListFriendsReq) (r *yim.ListFriendsRsp, err error) {
	var _args ListFriendsArgs
	_args.Req = Req
	var _result ListFriendsResult
	if err = p.c.Call(ctx, "ListFriends", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFriend(ctx context.Context, Req *yim.DeleteFriendReq) (r *yim.DeleteFriendRsp, err error) {
	var _args DeleteFriendArgs
	_args.Req = Req
	var _result DeleteFriendResult
	if err = p.c.Call(ctx, "DeleteFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckFriendship(ctx context.Context, Req *yim.CheckFriendshipReq) (r *yim.CheckFriendshipRsp, err error) {
	var _args CheckFriendshipArgs
	_args.Req = Req
	var _result CheckFriendshipResult
	if err = p.c.Call(ctx, "CheckFriendship", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddGroupMembers(ctx context.Context, Req *yim.AddGroupMembersReq) (r *yim.AddGroupMembersRsp, err error) {
	var _args AddGroupMembersArgs
	_args.Req = Req
	var _result AddGroupMembersResult
	if err = p.c.Call(ctx, "AddGroupMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveGroupMember(ctx context.Context, Req *yim.RemoveGroupMemberReq) (r *yim.RemoveGroupMemberRsp, err error) {
	var _args RemoveGroupMemberArgs
	_args.Req = Req
	var _result RemoveGroupMemberResult
	if err = p.c.Call(ctx, "RemoveGroupMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QuitGroup(ctx context.Context, Req *yim.QuitGroupReq) (r *yim.QuitGroupRsp, err error) {
	var _args QuitGroupArgs
	_args.Req = Req
	var _result QuitGroupResult
	if err = p.c.Call(ctx, "QuitGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListGroupMembers(ctx context.Context, Req *yim.ListGroupMembersReq) (r *yim.ListGroupMembersRsp, err error) {
	var _args ListGroupMembersArgs
	_args.Req = Req
	var _result ListGroupMembersResult
	if err = p.c.Call(ctx, "ListGroupMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateGroupInfo(ctx context.Context, Req *yim.UpdateGroupInfoReq) (r *yim.UpdateGroupInfoRsp, err error) {
	var _args UpdateGroupInfoArgs
	_args.Req = Req
	var _result UpdateGroupInfoResult
	if err = p.c.Call(ctx, "UpdateGroupInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProfiles(ctx context.Context, Req *yim.GetProfilesReq) (r *yim.GetProfilesRsp, err error) {
	var _args GetProfilesArgs
	_args.Req = Req
	var _result GetProfilesResult
	if err = p.c.Call(ctx, "GetProfiles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchUsers(ctx context.Context, Req *yim.SearchUsersReq) (r *yim.SearchUsersRsp, err error) {
	var _args SearchUsersArgs
	_args.Req = Req
	var _result SearchUsersResult
	if err = p.c.Call(ctx, "SearchUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProfile(ctx context.Context, Req *yim.UpdateProfileReq) (r *yim.UpdateProfileRsp, err error) {
	var _args UpdateProfileArgs
	_args.Req = Req
	var _result UpdateProfileResult
	if err = p.c.Call(ctx, "UpdateProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPresence(ctx context.Context, Req *yim.GetPresenceReq) (r *yim.GetPresenceRsp, err error) {
	var _args GetPresenceArgs
	_args.Req = Req
	var _result GetPresenceResult
	if err = p.c.Call(ctx, "GetPresence", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
