// Code generated by Kitex v0.16.3. DO NOT EDIT.
package logicservice

import (
	server "github.com/cloudwego/kitex/server"
	yim "github.com/yim/kitex_gen/yim"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler yim.LogicService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler yim.LogicService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
